### ISSUE TITLE
Files are showing once?

### ISSUE THREAD

**Issue by SylarRuby** [okonet/react-dropzone#124]
When I drop more than one files, I only see the last dropped file but in console I see the array of files. Somewhere along here is not right:

```
<div>{this.state.files.map((file) => <img src={file.preview} /> )}</div>
```

Edited:

files initial state only shows one array? Why?

**Comment by Tushant** [comment]
I am in the same boat.

**Comment by okonet** [comment]
I've just tested it on http://okonet.ru/react-dropzone/ with multiple files and it worked just fine. 

Here is the code: https://github.com/okonet/react-dropzone/blob/gh-pages/browser.js#L50-L56

If you still having issues with this, please build a simple example so I can take a look. Also, which browser is affected? I've tested in FF and Chrome.

**Comment by SylarRuby** [comment]
Strange. Ill have another go later

**Comment by okonet** [comment]
I'll close it for now.

**Comment by Tushant** [comment]
It is still the same

 var RenderPhotos = React.createClass({
    getInitialState: function () {
        return {
          files: []
        };
    },

    onDrop: function (files) {
       this.setState({files:files})
    },

    render: function () {
      return (
           <div>
                <h3>Photos can bring your space to life</h3>
                <p>Add photos of spaces to give more insight of your space </p>
                <hr/>
                <div className="col-md-12">
                  <Dropzone ref="dropzone" onDrop={this.onDrop}>
                    <div>Try dropping some files here, or click to select files to upload.</div>
                  </Dropzone>
                </div>

                <div className="row">
                  {this.state.files.length > 0 ?
                  <div className="gallery">
                    {this.state.files.map((file,id) => <li className='col-md-4' key={id}>
                                    <img src={file.preview} width={100}/>
                                    <div>{file.name + ' : ' + file.size + ' bytes.'}</div>
                                </li> )}
                  </div> : null}
                </div>
                <div className="row continueBtn text-right">
                    <button className="btn how-it-works pull-left" onClick={this.props.previousStep}>Back</button>
                    <button className="btn how-it-works" onClick={this.nextStep}>Next</button>
                </div>
          </div>
      );
    },

**Comment by okonet** [comment]
`this.state` doesn't have files. You need the state of Dropzone

**Comment by Tushant** [comment]
Shows unexpected token { while using showFIles function. Error is show  on const { files }=this.state;

**Comment by Tushant** [comment]
this does not show any files in template but is shown on console.

var RenderPhotos = React.createClass({
    getInitialState: function () {
        return {
        };
    },

    onDrop(files) {
        console.log('Received files: ', files);
        this.setState({
            files: files
        });
    },

    showFiles() {
        var files = this.state;
        console.log('files',files);

        if (!files.length) {
            return null;
        }

        return (
            <div>
                <h3>Dropped files: </h3>
                <ul className="col-md-4">
                    {
                        files.map((file, idx) => {
                            return (
                                <li key={idx}>
                                    <img src={file.preview} width={100}/>
                                    <div>{file.name + ' : ' + file.size + ' bytes.'}</div>
                                </li>
                            );
                        })
                    }
                </ul>
            </div>
        );
    },

    render: function () {
      return (
           <div>
                <h3>Photos can bring your space to life</h3>
                <p>Add photos of spaces to give more insight of your space </p>
                <hr/>
                <div className="col-md-12">
                  <Dropzone onDrop={this.onDrop}
                          style={style}
                          activeStyle={activeStyle}>
                    Try dropping some files here, or click to select files to upload.
                </Dropzone>
                {this.showFiles()}
                </div>
                <div className="row continueBtn text-right">
                    <button className="btn how-it-works pull-left" onClick={this.props.previousStep}>Back</button>
                    <button className="btn how-it-works" onClick={this.nextStep}>Next</button>
                </div>
          </div>
      );
    },
});

**Comment by okonet** [comment]
I have no idea but I assume Dropzone works fine? If this is the case, then please ask on StackOverflow or any other forums.

**Comment by Tushant** [comment]
I think there should be const {files}=this.state.files in showFiles().That worked for me.But still the images are not further added instead replaced by the current one.

**Comment by okonet** [comment]
No, this is not how spread operator works. You can refer to the example page here: https://github.com/okonet/react-dropzone/blob/gh-pages/browser.js#L38

**Comment by SylarRuby** [comment]
Let me get this straight. Does your example shows more than one file when uploaded/dropped? For I am seeing just one.

**Comment by okonet** [comment]
It show a list of files with previews (when available) for all dropped files. It doesn't do uploading or any processing.

**Comment by Tushant** [comment]
I am down in the mouth.It might be me doing wrong.I am sorry I am giving up.

**Comment by okonet** [comment]
Does it work for you on http://okonet.ru/react-dropzone/?

Here is how it should look like:

![2016-01-13 at 10 53](https://cloud.githubusercontent.com/assets/11071/12290795/00225260-b9e4-11e5-81be-8563cbdb0bd2.gif)

If answer is yes, then there is a problem in your code and you should ask on StackOverflow or somewhere else. If it looks differently for you, then please post a screen video.

**Comment by Tushant** [comment]
It happens like in the video but right away after dropping the files if I want to add some more then the previous images will be replaced by current one.

**Comment by okonet** [comment]
Yes, this is how it suppose to work. If you need another behavior, it's up to you to implement it that way.

**Comment by Tushant** [comment]
Sorry I thought I was doing wrong.It is superb for me now. I love this component.
Thanks
