### ISSUE TITLE
Fetch data to server using ajax?

### ISSUE THREAD

**Issue by Tushant** [okonet/react-dropzone#126]
How can i fetch data so that i can send to server using ajax ? I am using django tastypie for backend.Also there is no option for delete.

**Comment by okonet** [comment]
I'm sorry, but it seem you better search on StackOverflow. This is an issue tracker related to dropzone component, which doesn't include any data fetching on its own. It's a user's responsibility to implement server communication. See https://github.com/okonet/react-dropzone#uploads

**Comment by Tushant** [comment]
OK thanks but why delete option is not working ? Also when i try to add image one by one then the image is replaced by the current one instead of adding further.

**Comment by okonet** [comment]
AFIK there is no `delete` option in this component. What are you referring to? Also, I don't know why it's not working with the image. This is also not a part of this component and should be implemented on your side. Please ask these questions on StackOverflow.

**Comment by Tushant** [comment]
#124 This issue is same as i am having.
