### ISSUE TITLE
wrong build output @ v3.3.1

### ISSUE THREAD

**Issue by magalhas** [okonet/react-dropzone#128]
Just to let you know that the published package over `npm` is not correct. Inside the `lib` folder there's currently a `src` folder inside, which obviously shouldn't be there.

**Comment by okonet** [comment]
Thanks! I'll fix it ASAP

**Comment by okonet** [comment]
Should be fixed in 3.3.2

**Comment by magalhas** [comment]
I've just confirmed it :+1:
