### ISSUE TITLE
Provide web bundle

### ISSUE THREAD

**Issue by vlindhol** [okonet/react-dropzone#129]
I do not have access to a complete node environment and would like to build a fairly simple react page using only \<script\> includes. I tried doing this with react-dropzone, but even after a few changes (removing requires etc), the in-browser version of Babel can't handle the spread operator.

In other words, I would appreciate a web bundle version, the process is described e.g. here: http://krasimirtsonev.com/blog/article/distributing-react-components-babel-browserify-webpack-uglifyjs

**Comment by okonet** [comment]
This is a duplicate of #112 . Do you mind providing a PR for this one?

**Comment by okonet** [comment]
BTW I prefer webpack but don't mind if you use browserify.

**Comment by vlindhol** [comment]
As I said, I don't have access to a development environment (I'm at work). Might take a look at it at home if I have the time, although it might take a while!
