### ISSUE TITLE
Warning: Failed propType: Invalid prop `children` supplied to `Dropzone`, expected a single ReactElement. Check the render method of `DropzoneDemo`.

### ISSUE THREAD

**Issue by jamesmbowler** [okonet/react-dropzone#130]
Thanks for this add on- looks really cool. I'm using react 14.6, and trying to run what you have in your example page. It works, however, I'm getting this error. I'm new to react, so I'd appreciate any help.

**Comment by okonet** [comment]
This was fixed in https://github.com/okonet/react-dropzone/pull/121 so I guess you need to update to the latest version.
