### ISSUE TITLE
Dropping Image not setting files to input.

### ISSUE THREAD

**Issue by andrewuscf** [okonet/react-dropzone#131]
``` javascript
<Dropzone onDrop={this.onDrop} className="drop-zone text-center" name="building_photo_1"
                        inputProps={{size: '30', required: "true"}}>
             <i className="fa fa-upload fa-4x"/>
             <div className="drop-zone-text">
                   {!this.state.fileNames ?<div>Select files to upload<p>or drag and drop photo files</p></div>
                   : <div>{this.state.fileNames}</div>}
             </div>
</Dropzone>
```

Selecting files sets the files to the input perfectly, but when dropping the file the files are not being set to the input.

**Comment by okonet** [comment]
I don't understand this. Can you describe what are you expecting and what's happening? Also, please add a jsfiddle with an example that reproduces your problem.

**Comment by markbgh** [comment]
I'm experiencing this as well. When I upload a file by clicking on the Dropzone, it works fine, but dragging a file into the Dropzone doesn't change the value of the hidden input, and therefore it doesn't work if you're doing a non-ajax submission (like in a Rails form, for example), because it looks to the hidden input to figure out which file to upload.

**Comment by okonet** [comment]
Okay I see. Do you mind filing a PR with the fix for that.

**Comment by ihgrant** [comment]
As far as I can tell, it's not possible to set the files property on a file input using javascript, so this is _not a bug_ in react-dropzone.

The way I ended up working around this issue is by submitting the form using fetch, and storing the files that were dropped in state and adding them to a FormData instance created from the form, e.g.:
```js
    onDrop(acceptedFiles, rejectedFiles, e) {
        this.setState({
            files: acceptedFiles,
            filesWereDropped: !e.target.files || e.target.files.length === 0
        });
    }
    onSubmit(e) {
        e.preventDefault();
        let formData = new FormData(this.formRef);

        if (this.state.filesWereDropped) {
            /* if the file input has no files, check state for files and add
             * those to the form data. This is necessary because dragging
             * and dropping does set the files attribute of the file input,
             * and it is not possible to set it from javascript for
             * security reasons.
             */
            this.state.files.forEach(file => {
                formData.append('myfiles', file, file.name);
            });
        }

        // then POST your formData!
    }
```

**Comment by vikalpgupta-birdeye** [comment]
@okonet This is still an issue, dragging and dropping a file on dropzone does not update the filelist object, whereas in normal implementation of input type file dragging and dropping a file updates its corresponding filelist data. Please look into this.

**Comment by okonet** [comment]
@vikalpgupta-birdeye I'm open for the PR if you know how to implement this.

**Comment by micchyboy237** [comment]
So did anyone fix this issue?

**Comment by ihgrant** [comment]
@micchyboy237, not possible, as I explained above. It's a limitation put in place by browsers for security.

**Comment by JonnyBoy333** [comment]
@ihgrant In your solution to this problem above, you have the third property in onDrop that is the event. In my testing I am having problems accessing the target prop from the event. Whenever I try to do this I get warnings in the console and ultimately a `Cannot read property 'files' of null` error.

The warning reads like `index.js:2178 Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property "target" on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist().`

How did you get around this?

**Comment by okonet** [comment]
@JonnyBoy333 the warning looks like a bug at our side because we switched to Promises (https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L177) so we might need to persist the event before we call it here:

https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L209

Can you please report it in a separate issue with steps to reproduce and possible work on fixing it? Thanks!

**Comment by JonnyBoy333** [comment]
@okonet Looks like someone has already filed this issue in #646. I will track it over there.

**Comment by ihgrant** [comment]
Yeah, things have changed in the 2.5 years since I wrote that! You can probably save off a reference to the target and then use it in setState, e.g.
```js
    onDrop(acceptedFiles, rejectedFiles, e) {
        const target = e.target;
        this.setState({
            files: acceptedFiles,
            filesWereDropped: !target.files || target.files.length === 0
        });
    }
```
Or, as the warning says, call `e.persist()` before setState.

**Comment by Haraldson** [comment]
What about [this solution](https://stackoverflow.com/a/47522812/1209356)?

I guess, if what I was provided as an argument in the `onDrop` callback wasn‘t an ‘array of files’, but an actual `FileList`, it would be as simple as doing

```
const onDrop = useCallback(files => {
        inputRef.current.files = files
        setDragging(false)
    }, [])
```

**Comment by komalkedia** [comment]
> What about [this solution](https://stackoverflow.com/a/47522812/1209356)?
> 
> I guess, if what I was provided as an argument in the `onDrop` callback wasn‘t an ‘array of files’, but an actual `FileList`, it would be as simple as doing
> 
> ```js
> const onDrop = useCallback(files => {
>     inputRef.current.files = files
>     setDragging(false)
> }, [])
> ```
> 
> Edit: Actually, this works for me:
> 
> ```js
> const onDrop = useCallback((accepted, rejected, { dataTransfer: { files } }) => {
>     inputRef.current.files = files
>     // Custom code still needed to notify about changes, alternatively to trigger change events
> }, [])
> ```

It wont validate files. Validated files comes in accepted variable only.

**Comment by Haraldson** [comment]
Yes, I later noticed the same, so it would be really nice if the arguments were all somehow FileLists, or at least available as FileLists as well.

**Comment by IRediTOTO** [comment]
> What about [this solution](https://stackoverflow.com/a/47522812/1209356)?
> 
> I guess, if what I was provided as an argument in the `onDrop` callback wasn‘t an ‘array of files’, but an actual `FileList`, it would be as simple as doing
> 
> ```js
> const onDrop = useCallback(files => {
>     inputRef.current.files = files
>     setDragging(false)
> }, [])
> ```
> 
> Edit: Actually, this works for me:
> 
> ```js
> const onDrop = useCallback((accepted, rejected, { dataTransfer: { files } }) => {
>     inputRef.current.files = files
>     // Custom code still needed to notify about changes, alternatively to trigger change events
> }, [])
> ```

it not work for me, hmm. Anyone still follow this?

**Comment by IRediTOTO** [comment]
this is should be an error, if I click and choose file, the input tag will have file, but if drag it, no file apear in the input... I have many component to upload file so if tranfer child to parent component so complex I think.

**Comment by okonet** [comment]
Not sure it's supported by browsers even. Use the state variable to store the files instead and submit it manually.

**Comment by SerdarMustafa1** [comment]
> What about [this solution](https://stackoverflow.com/a/47522812/1209356)?
> 
> I guess, if what I was provided as an argument in the `onDrop` callback wasn‘t an ‘array of files’, but an actual `FileList`, it would be as simple as doing
> 
> ```js
> const onDrop = useCallback(files => {
>     inputRef.current.files = files
>     setDragging(false)
> }, [])
> ```
> 
> Edit: Actually, this works for me:
> 
> ```js
> const onDrop = useCallback((accepted, rejected, { dataTransfer: { files } }) => {
>     inputRef.current.files = files
>     // Custom code still needed to notify about changes, alternatively to trigger change events
> }, [])
> ```

Before using this I could click the input to upload a file but not drag and drop. After using this, it's the other way around. I can drop but not click.

I get an error saying:
Cannot read property 'files' of undefined'
``` const StyledDropzone = ({ id, setDocumentRef }) => {
  33 |   const onDrop = useCallback(
> 34 |     (accepted, rejected, { dataTransfer: { files } }) => {
     |                                           ^  35 |       inputRef.current.files = files;
  36 |     },
  37 |     []
  ```

**Comment by nimaa77** [comment]
for anyone that have the same issue, the solution in this blog post solved my issue

https://pqina.nl/blog/set-value-to-file-input/#updating-the-file-input-files-property


```ts
  useEffect(() => {
    if (!inputRef.current) return;

    const dataTransfer = new DataTransfer();
    acceptedFiles.forEach((file) => {
      dataTransfer.items.add(file);
    });

    inputRef.current.files = dataTransfer.files;

    // Help Safari out
    if (inputRef.current.webkitEntries.length) {
      inputRef.current.dataset.file = `${dataTransfer.files[0].name}`;
    }
  }, [acceptedFiles]);

```

**Comment by bernatfortet** [comment]
> for anyone that have the same issue, the solution in this blog post solved my issue
> 
> https://pqina.nl/blog/set-value-to-file-input/#updating-the-file-input-files-property
> 
> ```ts
>   useEffect(() => {
>     if (!inputRef.current) return;
> 
>     const dataTransfer = new DataTransfer();
>     acceptedFiles.forEach((file) => {
>       dataTransfer.items.add(file);
>     });
> 
>     inputRef.current.files = dataTransfer.files;
> 
>     // Help Safari out
>     if (inputRef.current.webkitEntries.length) {
>       inputRef.current.dataset.file = `${dataTransfer.files[0].name}`;
>     }
>   }, [acceptedFiles]);
> ```

This is fantastic!! Thank you so much!

**Comment by rolandjitsu** [comment]
This issue is related to https://github.com/react-dropzone/react-dropzone/issues/880. Another example on how to achieve a similar result can be found there and also in https://github.com/react-dropzone/react-dropzone/pull/1320 .
