### ISSUE TITLE
Drag and Drop from Google images or other window tab

### ISSUE THREAD

**Issue by cornerolive** [okonet/react-dropzone#133]
Hi,

It is possible to drag and drop an image from another window tab? When I do that it detects something but it's empty.

```
<DropzoneUpload getFile={this.getFileDragged} />

getFileDragged: function(item) {
   if (item.length > 0) {
        this.setState({
           files: item
       });
    }
},
```

Thank you!

**Comment by husa** [comment]
The exception is thrown
```
index.js:113 
Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
```
`droppedFiles` array is empty.

**Comment by cedricvidal** [comment]
+1

**Comment by janajri** [comment]
Also, seeing this when dragging an image between chrome tabs.

**Comment by okonet** [comment]
Seems like a duplicate of #255?

**Comment by ruiwei** [comment]
+1

**Comment by okonet** [comment]
Closing of inactivity

**Comment by anatoliyarkhipov** [comment]
Hey guys! I'm not sure what was the conclusions of the thread. I'm trying to DnD from a separate tab into my app (tried from Google Images and Wikipedia), and Dropzone doesn't react, no events are triggered. Any ideas how I can troubleshoot that? 🤔

**Comment by tonyketcham** [comment]
This issue should be reopened, would love to be able to accept images from other tabs!

**Comment by howlettt** [comment]
I ran into this https://github.com/react-dropzone/file-selector/issues/120 in Chrome when dragging images between tabs, updating to the latest file-selector npm version fixed it
