### ISSUE TITLE
How can I play the video file just dropped in?

### ISSUE THREAD

**Issue by ttyao** [okonet/react-dropzone#135]
Hi,

Once I loaded a video file from iphone to the dropzone, how can I play it as preview? Do you have any recommendation on where should I upload it to so that I can play from the same page?

Any comments are really appreciated!

**Comment by okonet** [comment]
Hi. This is out of scope of this library. For help and question you should use stackoverflow. Thanks

**Comment by ttyao** [comment]
so the preview of video doesn't work, right? I understand it is probably out of scope, but it is very related and just want to check if you have had encountered this when you are developing this.

**Comment by ffxsam** [comment]
@ttyao The magic of Google: http://stackoverflow.com/questions/14516947/how-to-preview-the-video-file-that-user-wants-to-upload-on-the-website-php-fii
