### ISSUE TITLE
Are file extensions supported in accept attribute?

### ISSUE THREAD

**Issue by djanosik** [okonet/react-dropzone#136]
I need to accept files by extension instead of MIME type. It is supported by browsers, but `react-dropzone` rejects all files when i specify an extension.

**Comment by okonet** [comment]
react-dropzone uses https://github.com/okonet/attr-accept, which is, in turn, based on a standard https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#Attributes. If your case is faulty, please file an issue in `attr-accept` repository. Before you submit it, please check if it is really a faulty implementation. Also, PRs welcome!

Thanks!

**Comment by okonet** [comment]
BTW it supports file extensions as well: https://github.com/okonet/attr-accept/blob/master/test/index.js#L111-L136

**Comment by djanosik** [comment]
Ok, I see where the issue is. `dataTransfer.items` do not have `name` property. Therefore it is not possible to compare file extensions and it will reject all file types.

**Comment by nofearOnline** [comment]
how can I accept only .stl files?

**Comment by rolandjitsu** [comment]
@nofearOnline should be as easy as `<Dropzone accept=".stl" />`.

**Comment by nofearOnline** [comment]
thanks. I have one more question: how can I limit the number of files?
I tried to use maxFiles = {1} and eventHandlers = maxfilesexceeded : function(file) { this.removeFile(file) } but they both did not work and bring the warning: React does not recognize the `eventHandlers` prop on a DOMelement, and React does not recognize the `maxFiles` prop on a DOM element.

**Comment by rolandjitsu** [comment]
@nofearOnline you get that error because there is no such property on the dropzone component. You can just slice the list of accepted files in the on drop cb.

**Comment by nofearOnline** [comment]
what do you mean by slice? how can I 'slice' the list?

**Comment by rolandjitsu** [comment]
`onDrop` emits a js array, so use `.slice(0, maxItems)`:

```js
class Basic extends React.Component {
  onDrop = acceptedFiles => {
    const files = acceptedFiles.slice(0, 10) // 10 max files
  }

  render() {
    return (
      <Dropzone
        onDrop={this.onDrop}
      >
        <p>Try dropping some files here, or click to select files to upload.</p>
      </Dropzone>
    );
  }
}
```
