### ISSUE TITLE
Cant drop file in Internet Explorer 9 

### ISSUE THREAD

**Issue by bekerov** [okonet/react-dropzone#137]
Hello. Thanks for lib. Im trying upload in IE9 and error in console
![image](https://cloud.githubusercontent.com/assets/2405629/12978457/fed0c8f0-d0e1-11e5-8b25-192557043955.png)

At index.js 
![image](https://cloud.githubusercontent.com/assets/2405629/12978473/23018462-d0e2-11e5-82dd-355a48c5ec42.png)

How i can resolve this trouble ?

**Comment by okonet** [comment]
This library doesn't support IE lower than 10. I will accept a PR if you choose to add a fix for it tho.

**Comment by lujck** [comment]
Solve problems in Internet explorer 9?
