### ISSUE TITLE
onDrop is being called with files that shouldn't be accepted

### ISSUE THREAD

**Issue by luisrudge** [okonet/react-dropzone#138]
IMO, if the file isn't accepted, it shouldn't be sent to the onDrop method

![dnd](https://cloud.githubusercontent.com/assets/941075/13029578/43875630-d277-11e5-915e-5ffe7df828d4.gif)

**Comment by luisrudge** [comment]
I just found out about `onDropAccepted`. IMO, this behavior is totally counter intuitive and there's no docs about this :( I think the onDrop method should be triggered only with valid files

**Comment by okonet** [comment]
Hey! Thanks for your feedback. I'd like to improve docs and examples (#123) but don't have much time to do so. If you could help and update README that would be great. There is also #104 which is related to this behavior. `onDropAccepted` was added later and I didn't want to break the API by introducing it. But it seems like a good idea after all. So if you'd like to help on this, your PR is more than welcome!

**Comment by luisrudge** [comment]
You want a PR to remove onDropAccepted or for improving docs?

**Comment by okonet** [comment]
Whatever you have time for now. Obviously removing code and changing API
will require much more work including adding tests and updating docs so I
guess adding these methods to README would be good as well.

Thanks!


Sincerely yours

Andrey Okonetchnikov

@okonetchnikov
http://okonet.ru

**Comment by luisrudge** [comment]
but are you good with me removing onDropAccepted and onDropRejected?

**Comment by okonet** [comment]
Yes, I think we should do that. 

If you do, please create a PR against the [4.0 branch](https://github.com/okonet/react-dropzone/tree/4.0)

**Comment by luisrudge** [comment]
Ok! I'll try to do this today

**Comment by laurentsmohr** [comment]
GUYS! This change needs to be reflected in the Docs. Was just wondering why onDropRejected didn't do anything.
Also I think its very intuitive to have all three: onDrop, onDropRejected and onDropAccepted, as their naming says exactly what they do.
