### ISSUE TITLE
onDragLeave won't call back when react-dropzone has input element as children

### ISSUE THREAD

**Issue by nqbao** [okonet/react-dropzone#140]
If i create a dropzone with input element as children, the dragleave callback won't be call correctly.

```
  <Dropzone disableClick multiple={false}>
       <div><input type='text' /></div>
  </Dropzone>
```

Here is the screenshot after drag in and dragout a while, the dragleave won't callback anymore

![input](https://cloud.githubusercontent.com/assets/177742/13083118/3ef1c970-d506-11e5-9c0b-99ecdf7eba28.gif)

**Comment by nqbao** [comment]
To clarify: if i replace the input tag with simple text then there is no issue at all.

**Comment by NervosaX** [comment]
I get this error as well.

**Comment by NervosaX** [comment]
This works around the issue by just not using the dropzone dragLeave, instead using a wrapper div.

@nqbao This might help you.

```javascript
<div onDragLeave={this.handleDragLeave.bind(this)}>
	<Dropzone
		className={classes}
		style={{}}
		onDrop={this.handleDrop.bind(this)}
		onDragEnter={this.handleDragEnter.bind(this)}>

		{this.state.dropEnter ? (
			<div>Drop image here</div>
		) : (
			<div>
				<Icon value="photo" />
				<div>Click to select an image or drag one here</div>
			</div>
		)}
	</Dropzone>
</div>
```

**Comment by NervosaX** [comment]
Further developments. If using > IE11, you can use the following to fix the above issue:

```scss
.dropzone {
  * {
    pointer-events: none;
  }
}
```

**Comment by nqbao** [comment]
It is  better but still very laggy, when you hover into the inner element of DropZone.

![dragzone](https://cloud.githubusercontent.com/assets/177742/13513875/e42d912c-e158-11e5-9d53-0b53469b0200.gif)

**Comment by okonet** [comment]
Is this still an active issue? Can someone create a PR to fix this?

I'm closing it of inactivity for now.

**Comment by romkri** [comment]
DragOver(e){
      if(this.dragTimer) clearTimeout(this.dragTimer);
      var me = this;
      this.dragTimer = setTimeout(function(){
          me.setState({drag:false});
      },100);

     e.preventDefault();
     this.setState({drag:true});
}
