### ISSUE TITLE
Accept multiple MIME types?

### ISSUE THREAD

**Issue by silvenon** [okonet/react-dropzone#141]
I would like my instance of Dropzone to only accept images, is there a way to do that? Since `accept` should be a string, therefore a single MIME type is supported.

**Comment by silvenon** [comment]
The solution is: `image/*`, but it can also be a comma delimited list of MIME types if necessary.

**Comment by moffsugita** [comment]
https://github.com/react-dropzone/react-dropzone/issues/391
