### ISSUE TITLE
Base64 data string of file

### ISSUE THREAD

**Issue by cbougatsa** [okonet/react-dropzone#146]
Hello and thank you for a great component!

Is there an easy way of converting the files passed to the onDrop event to base64? 

Thank you

**Comment by okonet** [comment]
Just convert to whatever you want in the `onDrop` callback. It gets the `files` object from the browser. See https://github.com/okonet/react-dropzone/blob/master/src/index.js#L98

**Comment by lonelydatum** [comment]
Maybe this example might help:

```
onDropHandler(files) {      
      var file = files[0]
      const reader = new FileReader();
      reader.onload = (event) => {
        console.log(event.target.result);
      };
      reader.readAsDataURL(file);
}
```

**Comment by ashfaqnisar** [comment]
> 
> 
> Maybe this example might help:
> 
> ```
> onDropHandler(files) {      
>       var file = files[0]
>       const reader = new FileReader();
>       reader.onload = (event) => {
>         console.log(event.target.result);
>       };
>       reader.readAsDataURL(file);
> }
> ```
You are simply awesome buddy!!!!!

**Comment by xama** [comment]
Hello how I can submit  the base64 converted file instead of simple file object ? thank you
