### ISSUE TITLE
Incorrect orientation on image taken with mobile device.

### ISSUE THREAD

**Issue by c0cky** [okonet/react-dropzone#147]
I'm taking a picture with my iPhone 5s and trying to upload a file on my desktop, the images orientation is incorrect.

**Comment by okonet** [comment]
I'm not sure this is related to the component. The only place that might be related to this is here: https://github.com/okonet/react-dropzone/blob/master/src/index.js#L92 and this is also a browser feature.

I've found this StackOverflow article: http://stackoverflow.com/questions/29752779/how-can-i-preview-image-before-uploading-with-the-correct-orientation-with-javas

I'd accept a PR that fixes it, but I'd rather keep the surface of this library minimal.

**Comment by c0cky** [comment]
I was just curious because Dropzone.js added a fix for this on the client side about 29 days ago. No worries, I understand if we want to keep this as minimalist as possible.

For anyone who finds this in the future what I'm going to do is just use [https://github.com/blueimp/JavaScript-Load-Image](url) in the onDrop and it automagically reorients the image based on the exif.

**Comment by okonet** [comment]
:+1:

**Comment by pukapukan** [comment]
If you are storing file in S3, you can use S3 item creation event to trigger Lambda to auto orient image using gm.

**Comment by Andriy-Kulak** [comment]
@camrongodbout can you explain how you ended up the JavaScript-Load-Image package in React? if I follow the package instructions and add the package as a script tag in index.html file, then I cannot use loadImage because it is undefined in my specific component. Also, I cannot import the package in my Component properly. Any quick tips would be greatly appreciated!

**Comment by manoj-makkuboy** [comment]
@Andriy-Kulak I created a wrapper for that purpose.

**Comment by pavelpashkovsky** [comment]
@Andriy-Kulak you can use this repo: (https://github.com/blueimp/JavaScript-Load-Image)

`npm i blueimp-load-image`

then:

`import loadImage from 'blueimp-load-image';`

**Comment by lounsbrough** [comment]
@manoj-makkuboy - `fix-image-rotation` doesn't work in IE11.

**Comment by adityay-perpetualny** [comment]
> I was just curious because Dropzone.js added a fix for this on the client side about 29 days ago. No worries, I understand if we want to keep this as minimalist as possible.
> 
> For anyone who finds this in the future what I'm going to do is just use [https://github.com/blueimp/JavaScript-Load-Image](url) in the onDrop and it automagically reorients the image based on the exif.

Could you please help me in implementing this?

**Comment by adityay-perpetualny** [comment]
> @Andriy-Kulak you can use this repo: (https://github.com/blueimp/JavaScript-Load-Image)
> 
> `npm i blueimp-load-image`
> 
> then:
> 
> `import loadImage from 'blueimp-load-image';`

This is pure javascript, how can we use this in react?

**Comment by jniyaz** [comment]
> @Andriy-Kulak I created a wrapper for that purpose. `$ npm install fix-image-rotation`. I am using it along with react-dropzeon in the onDrop function. It uses javascript-load-image internally.

Hi Manoj, trying your library, in onDrop method, seems not working here.. if you provide example, more appreciated. Thanks.
