### ISSUE TITLE
Upload to S3

### ISSUE THREAD

**Issue by siegesmund** [okonet/react-dropzone#148]
I am trying to upload to S3 directly from the browser using a pre-signed PUT url. In onDrop, I'm grabbing the files, and creating a pre-signed URL for each of them before putting them to S3. The problem is that in S3, they just show up as '[Object object]' or sometimes the '{preview: blob...}'  (basically a bit of text from the object). 

What is the File object type, and how can you properly format it so that you can use a PUT request to send the file to S3?

**Comment by siegesmund** [comment]
Figured it out... thanks for a great library!

**Comment by kristjanmik** [comment]
@siegesmund care to share your approach?

**Comment by siegesmund** [comment]
Hey @kristjanmik,
I don't remember precisely why I was having this problem but I remember that I was using the request library, and switching to a raw XMLHttpRequest solved the problem. In all likelihood, there's an option to pass to request to fix this, but I've stuck to using XMLHttpRequest as it's a little more transparent.

The essence of it is this:

`onDrop (files) {


}`

**Comment by kristjanmik** [comment]
Thanks @siegesmund. I found out a good approach to do this as well. 

Client:
`````javascript
import request from 'superagent'

request
  .put(url)
  .set('x-amz-acl','public-read')
  .send(file)
  .on('progress', e => {
    console.log('Percentage done: ', e.percent);
  })
  .end((error, res) => {
    if(error) return console.error('error',error)
    if(res.statusCode !== 200) return console.error('Wrong status code')

    //...success
  });
`````

And the server that generates the url:
`````javascript
import AWS from 'aws-sdk'
import mime from 'mime'

var bucket = new AWS.S3({
  params: {Bucket: 'yourbucket.foo.com'},
  region: 'eu-west-1' , signatureVersion: 'v4'
});

key = 'someuuid.png'

var params = {
    Key: key,
    Expires: 3600, //sec
    ContentType:mime.lookup(key),
    ACL:'public-read'
};

return new Promise( function(resolve,reject){
  bucket.getSignedUrl('putObject', params, function(err, url) {
    if(err) return reject(err)

    return resolve(url)
  })
}).then( (url) => console.log) //the url to use
``````

**Comment by richardzyx** [comment]
It seems that using @kristjanmik method on the client side does successfully put object to the S3 presigned url, but S3 somehow won't return any header with useful data such as eTag. Anyone has a fix for this? Is it another CORS related issue?

**Comment by jcjpsa** [comment]
How do you do this using `fetch` API has anybody been able to do so?

**Comment by hamzasaleem2** [comment]
if someone is still looking for this

https://github.com/hamzasaleem2/s3oosh.git
