### ISSUE TITLE
Feature: Example how to send files with fetch API

### ISSUE THREAD

**Issue by ivanbara** [okonet/react-dropzone#153]
Hi,

I've tried to use this with fetch API but have had trouble implementing it. If you have used this with fetch, could please provide and example of how to send files to middleware and receiving them?

**Comment by ivanbara** [comment]
Never mind, i noticed that onDrop not only sends files, but also the event, i can catch it and pass it to fetch api.

**Comment by jamestwiggle** [comment]
@ivanbara how did you make it work? I'm having a bit of trouble trying to get something similar working but no luck yet. If you don't mind helping me out on SoF for some points heres a link:
http://stackoverflow.com/questions/37473634/uploading-images-with-fetch-to-express-using-multer

or here on github:
#### server.js
```js
var storage = multer.diskStorage({
        destination: './public/users',
        filename: function (req, file, cb) {
            switch (file.mimetype) {
                case 'image/jpeg':
                    ext = '.jpeg';
                    break;
                case 'image/png':
                    ext = '.png';
                    break;
            }
            cb(null, file.originalname + ext);
        }
    });

var upload = multer({storage: storage});

app.use(upload.single('photo'));

app.post('/uploadUserImage', function (req, res) {
    console.log(JSON.stringify(req.body.photo)) // form fields
    console.log(req.photo) // form files
    console.log(req.file) // form files
    res.send(req.body.photo);
});
```

#### client.js
```js
    function uploadImage (image) {
      var formData = new FormData();
      formData.append('photo', image);
      fetch('http://localhost:8080/uploadUserImage/', {
        method:'POST',
         body: formData
      });
    }
```

**Comment by ivanbara** [comment]
Hi @jamestwiggle 
You can find my implementation on my github page: [https://github.com/ivanbara/reactimageservice]
Check these:
handleSubmit(e) in DropZonePlace.js and router.post('/upload',  (req, res)... in uploads.js
