### ISSUE TITLE
Dropped text/uri-list or text/html causes exception if the multiple prop is false

### ISSUE THREAD

**Issue by BJTerry** [okonet/react-dropzone#155]
If a dropzone is set to `multiple={false}` and a user drops something that is not an image file onto it (for example, an image from within their browser window, or a link), it causes a javascript error. This occurs even if the item doesn't match the `accept` property and so should be rejected. Here is an example: http://www.webpackbin.com/41KCncGRe

This doesn't occur if disablePreview is true.

In Firefox:

`TypeError: Argument 1 is not valid for any of the 2-argument overloads of URL.createObjectURL.`

In Chrome:

`Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.`

**Comment by okonet** [comment]
Thanks for reporting it. Do you mind creating a PR with the fix for it?

**Comment by Yevhen-Kryvdiuk** [comment]
Thanks, helped
