### ISSUE TITLE
Rename 'onDrop' in examples to something else?

### ISSUE THREAD

**Issue by JobLeonard** [okonet/react-dropzone#167]
I was stuck for two days [hunting an incredibly basic bug](https://gist.github.com/JobLeonard/80699f8caaadeec1ad9605cf6997dd91) because I did the binding wrong. I did not notice I did the binding wrong because

a) I'm a noob
b) onDrop was not null

Basically, using ES2015 I would normally see a "Type is null" error, but (I guess) because onDrop is always defined, being a built-in, I was not given this feedback. Feedback is necessary to fix point a) in the list above.

**Comment by okonet** [comment]
PR?

**Comment by okonet** [comment]
Please take a look at https://react-dropzone.js.org/ before proceeding. Is this clear enough?
