### ISSUE TITLE
processing image on server

### ISSUE THREAD

**Issue by mikejonas** [okonet/react-dropzone#176]
I'm using sharp to process images on the server side.  When I post the file to the server from dropzone though, I get the blob out of the request.body : { preview: 'blob:http%3A//127.0.0.1%3A3000/1451580a-b24f-478f-a9f7-338c0d790829' }.

Sharp takes: 
- A Buffer containing JPEG, PNG, WebP, GIF, SVG, TIFF
- Raw pixel image data
- A String containing the path to an image file, with most major formats supported.

How can I use react-dropzone to provide sharp a supported format? Or is it possible to convert the blob to one of these supported formats?

Thanks!!!

**Comment by mikejonas** [comment]
I got the solution over here http://stackoverflow.com/questions/37222718/image-uploading-how-to-get-the-right-format-of-image-data-for-server-side-proc . The module works great!

**Comment by jamestwiggle** [comment]
@mikejonas I'm trying to get something similar working but no luck yet. If you don't mind helping me out on SoF for some points heres a link:
http://stackoverflow.com/questions/37473634/uploading-images-with-fetch-to-express-using-multer

or here on github:
### server.js
```js
const app = express();

app.use(function (req, res, next) {
	res.setHeader('Access-Control-Allow-Origin', '*');
	res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, PATCH, DELETE, OPTIONS');
	res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With, content-type, authorization, accept, origin');
	res.setHeader('Access-Control-Allow-Credentials', 'true');

	if (req.method === 'OPTIONS') {
		res.status(200).end();
	} else {
		next();
	}
});

var upload = multer({ dest: './public/uploads'});

app.use(bodyParser.json());

app.use(morgan('dev'));

app.use(upload.single('photo'))

app.post('/uploadUserImage', function (req, res) {
	console.log(req.body) // form fields
	console.log(req.files) // form files
	res.status(204).end()
})
```

### client.js
```js
  files = files[0];
  var formData = new FormData();
  for (name in files) {
    formData.append(name, files[name]);
  }
    fetch('http://localhost:8080/uploadUserImage/', {
      method:'POST',
      body: formData
    });
```

**Comment by jamestwiggle** [comment]
@mikejonas I get the following response from the server:
<img width="166" alt="screen shot 2016-05-27 at 10 47 03 am" src="https://cloud.githubusercontent.com/assets/19610736/15611426/602b8f9a-23f8-11e6-82bf-0feb976fcc23.png">

However It doesn't get placed in the location specified in multer('./public/uploads'). What do you think I should do to manipulate/access the file because I also need to compress and resize images with sharp.
