### ISSUE TITLE
UglifyJS warnings

### ISSUE THREAD

**Issue by ayozebarrera** [okonet/react-dropzone#184]
There are some warnings on your code:

```
Condition always true [./~/react-dropzone/dist/index.js:2,0]
Dropping unreachable code [./~/react-dropzone/dist/index.js:4,0]
```

**Comment by okonet** [comment]
That's okay to have these — this means some dead code were eliminated. Or do you have any issues with the module after minifying it?

**Comment by ayozebarrera** [comment]
I'm not having any issues. 

But if there's some unreachable code I think you should delete it from your scripts.
