### ISSUE TITLE
how to set width and height, now it default 200px

### ISSUE THREAD

**Issue by sinkcup** [okonet/react-dropzone#185]
now width and height default 200px, how to set it?

![2016-06-16 16-09-27](https://cloud.githubusercontent.com/assets/4971414/16109709/c5f223b8-33dc-11e6-8bb5-46af750413fc.png)

**Comment by okonet** [comment]
You can pass `style` or `className` — same way you would style any other React element.

See https://github.com/okonet/react-dropzone/blob/gh-pages/browser.js for example.

**Comment by okonet** [comment]
I'd also prefer to keep this issue tracker for issues, not questions. If you have questions, please ask them on StackOverflow.
