### ISSUE TITLE
@3.5.1, windows (window 7) react-dropzone will do nothing after I selected a file.

### ISSUE THREAD

**Issue by hank7444** [okonet/react-dropzone#188]
#### browser: IE10, chrome

---

I recovery to @3.4.0, it works fine,

Have any ideas? 

#144 
#173

**Comment by okonet** [comment]
I've just deployed latest version to http://okonet.ru/react-dropzone/ and tested with Win7 in both IE10 and Chrome without any issues.

Can your issue be related to this change? https://github.com/okonet/react-dropzone/pull/173

**Comment by hank7444** [comment]
Sure!  my pleasure :0

**Comment by okonet** [comment]
Your response does not answer my question...

**Comment by hank7444** [comment]
I can't upgrade 4.0.0 by npm, it newest version is 3.5.1 on npm

**Comment by okonet** [comment]
Sorry, I don't follow. What 4.0.0? The latest version is 3.5.1. See https://github.com/okonet/react-dropzone/blob/master/CHANGELOG.md
