### ISSUE TITLE
About files

### ISSUE THREAD

**Issue by nikbelikov** [okonet/react-dropzone#190]
1. Click on Dropzone in http://okonet.ru/react-dropzone/
2. Select file

Console will write "Received files: 1 file"

Then select `<input type="file" accept="image/*" multiple="" style="display: none;">` in the inspector and go to the console, write $0.files, then you will have filelist, length 1. OK

If I do the same thing but DRUG & DROP file into the Dropzone, $0.files will have 0 length.

Why that?

**Comment by mrzou** [comment]
@nikbelikov Hi, I have the same problem before. But resoled it later. It's not the problem of DropZone Component. Maybe you misunderstood that. The onDrop event is listening div element instead of input. So you only get files from onDrop props

```
onDrop: function (files) {
    console.log('Received files: ', files);
},
```

That is it!

**Comment by nikbelikov** [comment]
Thanks!
