### ISSUE TITLE
Drop not working in Chrome

### ISSUE THREAD

**Issue by tocttou** [okonet/react-dropzone#191]
I have a functional component like this:
```
const singleInput = (props) => {

  function onDrop(file) {
    console.log(file);
  }

  return (
    <div className="ui container grid">
      <div className="centered row">
        <div className="ui three wide column">
          <Dropzone onDrop={onDrop}>
            <div>Try dropping some files here, or click to select files to upload.</div>
          </Dropzone>
        </div>
      </div>
    </div>
  );
};
```

Uploads work fine using drop or click on Firefox but on Chrome/Chromium only upload by click works.

```
➜  google-chrome --version
Google Chrome 51.0.2704.84 
➜  chromium-browser --version 
Chromium 49.0.2623.108 Ubuntu 16.04
```

**Comment by tocttou** [comment]
This seems to be a bug with Chrome actually as I am unable to see any files upload here as well: http://sarink.github.io/react-file-drop/demo/

But everything works in FF here as well.

**Comment by okonet** [comment]
It works for me on Mac OS X 10.11 in Chrome 51.0.2704.106 (64-bit)
![2016-06-28 at 10 03](https://cloud.githubusercontent.com/assets/11071/16408180/c548fbdc-3d17-11e6-80f9-6115a7254ba1.png)

**Comment by tocttou** [comment]
Yeah I confirmed it to working for others in Chrome/Chromium on lInux. Its an issue with my chrome install. Sorry to bother you. Thanks.

**Comment by eladlevy** [comment]
Any workaround for this?
I have the same issue with Google Chrome 51.0.2704.106. It happens when I drag the file from the bottom download bar that appears after you download a file.

**Comment by MaffooBristol** [comment]
Should be fixed whenever this is merged in: https://github.com/okonet/react-dropzone/pull/225

**Comment by okonet** [comment]
I've just published https://github.com/okonet/react-dropzone/releases/tag/3.6.0 with a possible fix for this one.

**Comment by filoscoder** [comment]
Same issue on Chrome 88, but solved after updating to 90 👍🏾

**Comment by omar4digital** [comment]
is the issue back on chrome 104 ?

**Comment by mustafaucr** [comment]
> is the issue back on chrome 104 ?

Yes I use version 107 and it does not work. FF works properly
