### ISSUE TITLE
Chrome - onDrop not being called when dragging from downloads bar

### ISSUE THREAD

**Issue by eladlevy** [okonet/react-dropzone#195]
![dropzonebug](https://cloud.githubusercontent.com/assets/4246412/16565642/5fdad4e6-4217-11e6-8866-4ee581b8d618.gif)

I can reproduce this bug only when dragging for the downloads bar. I'm using Chrome 51.0.2704.106. 
Is it a Chrome bug? any workarounds for this issue?

**Comment by okonet** [comment]
Duplicate of #191?

**Comment by eladlevy** [comment]
Possibly.  I wasn't sure if he was talking about the same drag scenario

**Comment by MaffooBristol** [comment]
I don't think this is necessarily related to #191, but I think it is definitely an issue. The standard Dropzone.js library works fine when dragging from the downloads bar, but react-dropzone doesn't work.

Chrome 52.0.2743.116 (64-bit), Mac 10.9.5

**Comment by eladlevy** [comment]
Yes. still reproducible with the latest version of Chrome 52.0.2743.116 (64-bit)

**Comment by eladlevy** [comment]
So apparently the weird fix in #74 solves this issue
adding this line:
```e.dataTransfer.dropEffect = 'copy';```

**Comment by MaffooBristol** [comment]
Great, just needs to be PRed then!

**Comment by okonet** [comment]
Should be fixed in https://github.com/okonet/react-dropzone/releases/tag/3.6.0
