### ISSUE TITLE
don't publish .babelrc

### ISSUE THREAD

**Issue by blaenk** [okonet/react-dropzone#198]
When I install, I get an error when I build with webpack because it says it can't find the babel plugin `add-module-exports` which is specified in react-dropzone's `.babelrc`. It is my understanding that this file shouldn't be published to npm at all.

Searching around I found [this](https://github.com/callemall/material-ui/issues/3200) which seems to resolve it by being specific about which files are published to the npm registry, by specifying something like `"files": "src/index.js"`.

This way the `.babelrc` won't end up on the user's system, so babel won't attempt to obey it. I had to remove the `.babelrc` file myself from `node_modules/react-dropzone/.babelrc` to resolve this.

**Comment by okonet** [comment]
You shouldn't compile sources from `node_modules`. Exclude them in your webpack config.

**Comment by okonet** [comment]
Also, in `package.json` the `main` field is set to the compiled JS file.

**Comment by blaenk** [comment]
Thanks! Sorry for the noise, I hadn't realized something went wrong in my webpack config.
