### ISSUE TITLE
request for onCancel

### ISSUE THREAD

**Issue by flyon** [okonet/react-dropzone#199]
I want to change the UI if the user opened the file dialog but clicked cancle or closed the dialog. 
If this is already possible please tell me how, if not consider it a feature request

**Comment by okonet** [comment]
I'm not accepting feature requests since I don't have time to work on this library. But I'll be happy to merge a PR for this one. It sounds useful to me. Please don't forget to add tests before you submit it. Thanks!

**Comment by anuragCES** [comment]
Added a PR for this issue. Kindly review. https://github.com/okonet/react-dropzone/pull/237

**Comment by anuragCES** [comment]
@okonet 

Thank you reviewing the PR.

I have made code review changes. Kindly review. https://github.com/okonet/react-dropzone/pull/237

**Comment by okonet** [comment]
Done in https://github.com/okonet/react-dropzone/pull/237
