### ISSUE TITLE
Update Dropzone input field method?

### ISSUE THREAD

**Issue by colegeissinger** [okonet/react-dropzone#201]
I'm utilizing [React Cropper](https://github.com/roadmanfong/react-cropper) with Dropzone and I have everything wired up so it is working except one part.

I need to be able to update the input field that contains my image (I'm only supporting a single image instead of multiple). Can anyone provide some more clarifications if this is possible with this component?

I have cropper returning a new Blob that matches the same format that Dropzone creates, but I don't see any clear paths to updating the input field. I would assume a method that would allow me to programmatically add a new file or perhaps the trick is within `inputProps`? I'm just not clear how to utilize `inputProps` if that is the key.

**Comment by anorudes** [comment]
+1

**Comment by okonet** [comment]
I don't think you can do that. Instead, write your custom upload for the blob you get.
