### ISSUE TITLE
Active state passed on as prop to children

### ISSUE THREAD

**Issue by aymericbouzy** [okonet/react-dropzone#204]
I would like to style the children according to the active state, not only the surrounding component.
One way to do this would be to provide a `renderChild` prop, which would be a function taking the boolean `active` as argument.
Maybe there is some other way I didn't think of?

**Comment by okonet** [comment]
What you want is just passing the active state flag down the tree as a prop. PR?

**Comment by aymericbouzy** [comment]
What you suggest makes more sense. I'll look into this, I'll keep you posted.

**Comment by aymericbouzy** [comment]
Now that I have more experience with React, it seems to me that you cannot pass them as prop : children are rendered before Dropzone renders, it's too late to pass props to them. You could rather use something like context, but it doesn't seem designed to do that. 

`react-virtualized` uses a nice syntax I think. In this situation, it would allow to have this situation : 

```jsx
<Dropzone onDrop={this.onDrop}>
  {(active) => {
    if (active) {
      return <ActiveDropzoneContent />
    } else {
      return <InactiveDropzoneContent />
    }
  }}
</Dropzon />
```

I find it very readable, and not very difficult to implement. I can do a PR if you approve allowing such syntax (on top of the current one).

**Comment by okonet** [comment]
It's totally possible to extend childrens props. I also like function syntax. It could do both I think. Please feel free to create a PR and let's discuss in it.
