### ISSUE TITLE
Documentation for Pure Javascript unsigned direct upload to Cloudinary

### ISSUE THREAD

**Issue by schmidsi** [okonet/react-dropzone#207]
Hi 

I spent a vast amount of time figuring out how to use your component to directly upload images to Cloudinary. For simplicity I used [unsigned direct uploads from the browser](http://cloudinary.com/blog/direct_upload_made_easy_from_browser_or_mobile_app_to_the_cloud).

I don't know where to put this? In the Wiki? A fork of the README.md?

Here is the onDrop handler:

``` javascript
  drop: (files) => {
    console.log('DROP', files);

    files.forEach((file) => {
      const data = new FormData();
      data.append('file', file);
      data.append('api_key', YOUR_API_KEY);
      data.append('timestamp', Date.now() / 1000);
      data.append('upload_preset', YOUR_UPLOAD_PRESET);

      const request = new XMLHttpRequest();
      request.upload.addEventListener('progress', (event) => {
        console.log('progress', event);
      });
      request.addEventListener('load', (event) => {
        console.log('success', event);
      });
      request.addEventListener('error', (event) => {
        console.error('Error with upload', event);
      })
      request.open('POST', 'https://api.cloudinary.com/v1_1/YOUR_CLOUD_NAME/image/upload', true);
      request.send(data);
    });
  }
```

Note: Replace YOUR_CLOUD_NAME, YOUR_API_KEY and YOUR_UPLOAD_PRESET with your corresponding values. To create a upload preset, [go to your settings page](https://cloudinary.com/console/settings/upload) in cloudinary and create a new unsigned upload preset.

**Comment by okonet** [comment]
Hey! I think the blog post is more appropriate for stuff like this. I could add a link into the README.

**Comment by okonet** [comment]
BTW I just saw this: https://css-tricks.com/image-upload-manipulation-react/?utm_source=javascriptweekly&utm_medium=email

**Comment by NitroBAY** [comment]
'Waste amount of time' describes well my feeling.
I still cannot believe that a service which aiming to store image doesn't explain anywhere how to upload images (obviously from the browser from js, I think it's what most dev wants).
