### ISSUE TITLE
Deprecation warnings with React 15.3.0

### ISSUE THREAD

**Issue by fpayer** [okonet/react-dropzone#209]
I installed react-dropzone using npm and webpack and noticed that when it loads on the page, I get a ton of warnings from React. The warnings are along the lines of this:

```
Warning: You are manually calling a React.PropTypes validation function for the `onDrop` prop on `Dropzone`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
```

Is there an ETA for moving away from this deprecated functionality or am I not using the lib properly?

**Comment by okonet** [comment]
Hey! Would you like to submit a PR?

**Comment by fpayer** [comment]
I can't seem to track down the code responsible for causing the warnings. The link in the warning doesn't seem to show any example applicable for this lib.

**Comment by tomprats** [comment]
I'm running into this issue as well but it looks like Dropzone is using PropTypes in the correct way. I can't figure out why the warning is being generated.

**Comment by XXChester** [comment]
+1

**Comment by topgun743** [comment]
Seems like no one interested in removing this warning in source code or doing some fix for it there.

**Comment by topgun743** [comment]
OK, I used the source code of react-dropzone (src/index.js) directly in my app and now the warning not showing anymore. Not sure why.

**Comment by okonet** [comment]
Seems like the compiled source is affected? But this isn't reproducible on the demo page afaik. Can someone post a steps to reproduce or even better create a repo?

**Comment by avidant** [comment]
All you need to do is `import PropTypes from 'prop-types';` in index.js and recompile. Would it be possible for this to be added @okonet?

**Comment by okonet** [comment]
We already doing this: https://github.com/okonet/react-dropzone/blob/master/src/index.js#L4
