### ISSUE TITLE
Unknown props warnings when working with React 15.3.0

### ISSUE THREAD

**Issue by dorsha** [okonet/react-dropzone#211]
`Warning: Unknown props 'disableClick', 'disablePreview', 'global' on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop`

The problem is here:
https://github.com/okonet/react-dropzone/blob/master/src/index.js#L224

**Comment by zivl** [comment]
how this issue closed? is there a solution? was it solved in a later version of `react-dropzone`

**Comment by okonet** [comment]
It should be closed on latest version.
