### ISSUE TITLE
This component doesn't define main assets in bower.json.

### ISSUE THREAD

**Issue by LeKristapino** [okonet/react-dropzone#214]
Hi,

I am trying to use this component with Rails project through rails-assets, but it requers a bower file in order to install it ( I guess). Since I am not so familiar with front-end bundlers, would it be possible for you to add a bower.json file?

**Comment by okonet** [comment]
No, bower is basically a dead project at this time point. Just use `npm install react-dropzone` and add the dependency to your `package.json`
