### ISSUE TITLE
How to get absolute path for server-side node cloudinary upload?

### ISSUE THREAD

**Issue by acomito** [okonet/react-dropzone#217]
I need to pass the absolute path to cloudinary:

http://cloudinary.com/documentation/node_integration#getting_started_guide

like:

```
cloudinary.uploader.upload("my_picture.jpg", function(result) { 
  console.log(result) 
});
```

But when I pass it `files[0].preview`  I get:

```
{ error:
I20160825-10:52:30.652(-4)?    { [Error: ENOENT, open 'blob:http://localhost:3000/063d993a-ef56-4941-8d9f-e6219869f6a0']
I20160825-10:52:30.653(-4)?      errno: 34,
I20160825-10:52:30.653(-4)?      code: 'ENOENT',
I20160825-10:52:30.653(-4)?      path: 'blob:http://localhost:3000/063d993a-ef56-4941-8d9f-e6219869f6a0' } }
```

or `files[0].name` I get:

`{ error: { [Error: ENOENT, open 'my_picture.jpg'] errno: 34, code: 'ENOENT', path: 'my_picture.jpg' } }`

I'm using it with meteor 1.3-- although I don't think that would matter.

**Comment by okonet** [comment]
I don't think this is in the library scope. Please ask the question on StackOverflow. Closing it here.
