### ISSUE TITLE
'accept' prop doesn't completely support file extensions

### ISSUE THREAD

**Issue by charliematters** [okonet/react-dropzone#218]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input), file inputs can accept a list of file extensions for accepted file types. The 'accept-attr' library that you are using, however, does not.

I can specify `<Dropzone accept='.jpg .png' />` which is passed correctly to the hidden file input (and therefore the windows file picker), however the active class is never set.

**Comment by okonet** [comment]
Please report this to attr-accept and provide your use case since I'm not sure what you mean exactly.

**Comment by okonet** [comment]
Also, I don't think your example is valid according to spec:

> A file extension starting with the STOP character (U+002E). (E.g.: ".jpg,.png,.doc")
A valid MIME type with no extensions
audio/* representing sound files HTML5
video/* representing video files HTML5
image/* representing image files HTML5

**Comment by charliematters** [comment]
You are correct - my example is wrong. Sorry!

Even with the comma in the string, I can't get the active class to get set, so I will try it out and include some sample code

**Comment by charliematters** [comment]
Ok, after further inspection my issue is that the file name is not being passed to the accept library (causing the accept library to fail). 

Slight complication is that the error appears on an older version of Chrome, which I can't replicate outside of work, so I will close this defect.
