### ISSUE TITLE
Not working on Android when building with Cordova

### ISSUE THREAD

**Issue by domhede** [okonet/react-dropzone#224]
When running on the Android Emulators it is working as expected.  However after installing the APK on a real device Dropzone component is not doing anything.

Happening on Android 4.4.2
I think this is a Cordova Issue

**Comment by okonet** [comment]
Why are you using it on mobile devices? It's not designed for them. And what do you except it to do?

**Comment by domhede** [comment]
Cordova takes the app and packages it as a Native App.  Since it uses the webview the app should behave just like a mobile browser.

We are using React-Dropzone to handle all the file uploads.  It works well with Cordova and iOS.  Now the only issue for Android is on 4.4.2.  It seems that this OS has some know issues.  It seems like nothing I do can make work, so I was just reaching out to see if you'd had any experience with it.

At the moment the best option seems to use Crosswalk instead of the native webview.  Only issue now is that the app crashes when the camera dialog begins.

**Comment by okonet** [comment]
> We are using React-Dropzone to handle all the file uploads. It works well with Cordova and iOS. 

I don't get it. How are you using dropzone on mobile devices? This library is built upon drag'n'drop API which doesn't exist on mobile devices.

**Comment by domhede** [comment]
We are using the drag and drop function on Desktop and on mobile we just have the file input field render as a button.

**Comment by okonet** [comment]
I think in your case I woudn't include the react-dropzone for mobile version at all. Since you're creating a separate build (AFAIU) I think it's better just to conditionally include `<input type='file'/>` for mobile devices. 

I'll close this one since this lib isn't targeting Android or iOS if it's okay.
