### ISSUE TITLE
Width and Height properties on file object

### ISSUE THREAD

**Issue by Ghosh** [okonet/react-dropzone#227]
Dropzone seems to have the file width, height, ratio etc available on drop, ex - https://github.com/enyo/dropzone/blob/master/dist/dropzone.js#L191-L192

Is there a way to get the same data in react-dropzone?

**Comment by okonet** [comment]
Looking at their code https://github.com/enyo/dropzone/blob/master/dist/dropzone.js#L1109 I see that it's not a part of the standard, so I don't think this will be included. But you can borrow this code from them and implement your own size getter or use something like https://www.npmjs.com/package/browser-image-size.

**Comment by adeelibr** [comment]
@okonet i think this is an important feature and should be included in the libraries API itself

**Comment by okonet** [comment]
@adeelibr feel free to propose the API and implement it.
