### ISSUE TITLE
Can not upload multiple photos on my android device

### ISSUE THREAD

**Issue by duong** [okonet/react-dropzone#228]

**Comment by Arturszott** [comment]
What kind of device do you have? I've found out that non chrome device custom browser do not support multi upload.

**Comment by duong** [comment]
thank you for your answer, 
sorry for my missing description, for now I still have this issue.  Currently on my android device when upload popup  shown. There are some image folders open such as Photos, Image, application, gallery, facebook photo, one driver photo etc. When I click on photos folder and choose 2 pictures, then click done button, There was only image uploaded, please see the followings screenshots on my device.
please take a look and give me a advice, thanks 
![2017-02-24_8-50-47](https://cloud.githubusercontent.com/assets/830319/23287253/d774e75c-fa6e-11e6-9c15-14475d43a21a.jpg)
![16865129_376860826013022_6367305632635169983_n](https://cloud.githubusercontent.com/assets/830319/23287254/d79de562-fa6e-11e6-8f08-5f7add1fc092.jpg)
![16807132_376860832679688_4399419514957393295_n](https://cloud.githubusercontent.com/assets/830319/23287255/d7b60bb0-fa6e-11e6-94f2-9cd16cb7cf18.jpg)

**Comment by duong** [comment]
I''m now using Sony Experia with android version 6.0.1

**Comment by okonet** [comment]
Feel free to submit your fix as a PR

**Comment by duong** [comment]
I could not fix this by my self

**Comment by okonet** [comment]
I don't think this is an issue with this lib rather than with the browser/device. Feel free to re-open if you have something to add here. Otherwise, I'd ask on StackOverflow or other forums.
