### ISSUE TITLE
Question: How to detect wheter a file with invalid mimeType has been dropped

### ISSUE THREAD

**Issue by indianscout** [okonet/react-dropzone#229]
react-dropzone supports mimeType filtering. How can I detect wheter a dropped file has been declined by the filter? The _onDrop_ handler seems not to be executed in such a case, it seems to fail silently...

Any idea how to deal with that...?

**Comment by okonet** [comment]
You can pass a callback for the `onDropRejected` callback:

https://github.com/okonet/react-dropzone/blob/master/src/index.js#L117

**Comment by indianscout** [comment]
Exactly what I'm looking for :+1:
