### ISSUE TITLE
CSS Modules don't appear to be supported

### ISSUE THREAD

**Issue by rjatkinson2** [okonet/react-dropzone#234]
Utilizing standard css module syntax (shown below), the className is not passed to the component. Consequently, the default styles kick in. Using the same code below, directly assigning `className="green"` will override the class and remove the default styles (based on internal boolean).

Is there an intent to support CSS Modules - or am I possibly misunderstanding and this is a CSS Module + npm package issue.

```
import React from 'react';
import Dropzone from 'react-dropzone';
import styles from './styles.css';

const Upload = (props) => (
  <div className={styles.container}>
    <Dropzone
      onDrop={props.handleDrop}
      className={styles.drop}
      activeClassName={styles.active_drop}
    >
      <p>DRAG FILES INTO THIS WHITE BOX</p>
    </Dropzone>
  </div>
);

Upload.propTypes = {
  handleDrop: React.PropTypes.func.isRequired,
};

export default Upload;
```

Update: I can certainly get away with activeStyle prop using inline styles, so this is more of a feature request. However, I seem to get the same behavior for child components, which makes the inline styles pretty ungainly.

**Comment by okonet** [comment]
It should work as expected with CSS modules. Should be a bundling issue. Check if it is a string by logging it.

**Comment by Lucretius** [comment]
I see this is an old issue, but I just pulled down the latest react-dropzone, and I am using CSS modules in my project.  I was able to confirm that CSS module support appears to work just fine, if you felt like you wanted to close this issue.

**Comment by okonet** [comment]
Thanks!
