### ISSUE TITLE
Can't add pictures on macbook / safari?

### ISSUE THREAD

**Issue by anomaly44** [okonet/react-dropzone#235]
I was visiting a client and she told me she couldnt add picture on her mac / safari. I tried dragging and picking, when dragging, nothing happens. I see the dropzone responding to the file, not showing an error or anything.
can it have something to do with my ondrop? 

```javascript
onDrop(newfiles) {
    const imgFiles = newfiles.filter(file => {
      const regexp = /image\//;
      return file.type.match(regexp);
    });
    this.props.addPictures(imgFiles);
  }
```
really puzzled, since it works fine on windows and linux for me.

**Comment by okonet** [comment]
`file` is an object so I'm not sure how it can work on win/Linux. 

Also, you are looking for `onDropAccepted` method.

**Comment by anomaly44** [comment]
I've switched some things around, and it works better now, has a better experience. I still seem to be having trouble on iphones though. But that's probably a safari problem on it's own. Thanks for this package!

**Comment by seenickcode** [comment]
@anomaly44 , could you cite how you got it to work?  It seems for me dropping in jpg images doesn't work on Safari yet it works on other browsers.

**Comment by anomaly44** [comment]
instead of using the file locations to later upload the file, I process the files immediately when they are dropped in, using the canvas and FileReader. And i save the processed files in an array, and I upload the processed data later. I hope this makes sense :)
```javascript
onDropAccepted(newfiles) {
    newfiles.map(img => {
      const reader = new FileReader();
      reader.readAsDataURL(img);
      reader.onload = (event) => {
        const dataUrl = event.target.result;
        const image = new Image();
        image.src = dataUrl;
        image.onload = () => {
          this.props.addPicture(resizeImage(image, 1600, 1200));
        };
      };
    });
    this.setState({ showNotAcceptedError: false });
  }
```

```javascript
function resizeImage(image, maxWidth, maxHeight, quality) {
  const canvas = document.createElement('canvas');

  let width = image.width;
  let height = image.height;

  if (width > height) {
    if (width > maxWidth) {
      height = Math.round(height * maxWidth / width);
      width = maxWidth;
    }
  } else {
    if (height > maxHeight) {
      width = Math.round(width * maxHeight / height);
      height = maxHeight;
    }
  }

  canvas.width = width;
  canvas.height = height;

  const ctx = canvas.getContext('2d');
  ctx.drawImage(image, 0, 0, width, height);
  return canvas.toDataURL('image/jpeg', quality);
}
```

**Comment by seenickcode** [comment]
Ok I'll try this out. But my issue was the 'onDrop' function's
'acceptedFiles' parameter was always an empty array for Safari and JPGs
(not PNGs).  Did you experience this problem as well?

**Comment by anomaly44** [comment]
I didnt have a mac available for testing so can't say for sure, but switching from onDrop to onDropAccepted might be what solved the problem.
