### ISSUE TITLE
unable to install react-dropzone UNMET PEER DEPENDENCY error

### ISSUE THREAD

**Issue by sreenathchakkingal** [okonet/react-dropzone#236]
i get the following error when i try to install react-dropzone : 
npm install --save react-dropzone

finchakks@1.0.0 E:\codebase\myreact\finchakks
+-- UNMET PEER DEPENDENCY react@15.2.1
+-- UNMET PEER DEPENDENCY react-dom@15.2.1
`-- react-dropzone@3.6.0
  `-- attr-accept@1.0.3

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN optional Skipping failed optional dependency /webpack/watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN react-d3-basic@1.6.11 requires a peer of react@^0.14.7 but none was installed.
npm WARN react-d3-basic@1.6.11 requires a peer of react-dom@^0.14.7 but none was installed.
npm WARN react-data-grid@1.0.39 requires a peer of react@~0.14.6 but none was installed.
npm WARN react-data-grid@1.0.39 requires a peer of react-dom@~0.14.6 but none was installed.
npm WARN ron-react-autocomplete@3.0.1 requires a peer of react@~0.14.6 but none
was installed.
npm WARN ron-react-autocomplete@3.0.1 requires a peer of react-dom@~0.14.6 but none was installed.

**Comment by okonet** [comment]
Yes, that's correct if you haven't installed the wrong/incompatible version of `react` and `react-dom` packages.
