### ISSUE TITLE
Allow array for accept parameters

### ISSUE THREAD

**Issue by cjtafoya** [okonet/react-dropzone#243]
When passing in an array of mime types, it is correctly limiting available selections for the onClick file selector (non-accepted files are greyed out), but drag and drop does not work and it throws an error in the console saying that a string should be passed. Would it be possible to enable an array of mimetypes?

**Comment by okonet** [comment]
Is this a part of the standard. I'm sure I didn't see that `<input type="file">` accepts an `array` as `accept` attribute. Mind pointing to the spec?

If it is a part of the standard, I'm happy to accept a PR for https://github.com/okonet/attr-accept which implements this behavior in JS.

**Comment by okonet** [comment]
I've created an issue there: https://github.com/okonet/attr-accept/issues/3
