### ISSUE TITLE
Update README, this.refs is deprecated

### ISSUE THREAD

**Issue by olalonde** [okonet/react-dropzone#246]
Apparently, refs shouldn't be assigned a string anymore: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-string-refs.md#prevent-using-string-references-no-string-refs

Maybe update the `ref` part of the README to:

```
      <Dropzone ref={c => { this.dropzone = c }}>
```

**Comment by okonet** [comment]
Sure. Make a PR and I'll merge it! Thanks.

**Comment by olalonde** [comment]
Thx @tkh44 @okonet
