### ISSUE TITLE
MS IE11 and Edge error on example page

### ISSUE THREAD

**Issue by bmueller-sykes** [okonet/react-dropzone#248]
Hi,

On this page:

http://okonet.ru/react-dropzone/

...if you attempt to drag in an image (haven't tested other file types yet), when you hover over the drop target, you get a script error. The console shows:

```
SCRIPT16389: Unspecified error.
script.js (1739,8)
```

If I click into the error, Edge shows the error here:

```
{
key: 'onDragOver',
value: function onDragOver(e) {
e.preventDefault();
e.stopPropagation();
e.dataTransfer.dropEffect = 'copy'
return false;
}
}
```

It appears that the error is on this line:

`e.dataTransfer.dropEffect = 'copy'`

...because right after that line, the Edge console shows "unspecified error".

Maybe this is a bug in MS browsers themselves:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5184459/

In any event, I dug into the source code and just commented out the `dropEffect` line, and that seemed to take care of the problem. How crucial is that to react-dropzone overall?

I'm digging the library otherwise! Thanks!
Ben

**Comment by bmueller-sykes** [comment]
Sorry; just circling back to this. I'm happy to attempt to a pull request for this, but the only solution that works appears to be to just remove the "dropEffect" line, so the PR wouldn't be all that broad in scope. However, i didn't know if `dropEffect` was crucial to the library in any way that I simply cannot see, so I was reluctant to make a move.

**Comment by okonet** [comment]
I've just tested with Edge and everything works fine. Can you be more specific what steps to reproduce I need?

**Comment by okonet** [comment]
I can reproduce in IE11 though...

**Comment by okonet** [comment]
Yes, I think we could remove `dropEffect` in IEs for now. So if you can make a PR that would be great.

**Comment by bmueller-sykes** [comment]
Okay, will do! It'll be my first PR on a public library, so be gentle if I don't get the process quite right the first time. (-;

**Comment by bmueller-sykes** [comment]
okay. PR created.

**Comment by skotfred** [comment]
IE is often very picky about missing semicolons at the end-of-line in javascript,  that problematic line is missing one.
e.dataTransfer.dropEffect = 'copy'

**Comment by SpudNyk** [comment]
This issue has regressed and now happens again in IE 11
