### ISSUE TITLE
Problem with onDrop and state.files update

### ISSUE THREAD

**Issue by OriaLogic** [okonet/react-dropzone#249]
Hello,
Not a big issue but I have a problem with the onDrop method from the example:
```
onDrop: function (files) {
   this.setState({
        files: files
   });
},
```

The parameter ```files``` is supposed to be the array of uploaded files, but to me it is just the last file I uploaded wrapped in an array of length 1, so the example does not work if I want to upload multiple files. I find it quite normal as we do not pass the files array as prop to the Dropzone component so it cannot know the previous files uploaded.

Am I the only one having this issue?
Thanks for the good work

**Comment by okonet** [comment]
```js
onDrop: function (files) {
   this.setState({
        files: this.state.files.concat(files)
   });
}
```
