### ISSUE TITLE
Weird behaviour in IE with accept='text/*'

### ISSUE THREAD

**Issue by andschdk** [okonet/react-dropzone#256]
I'm using this component for CSV upload. It works well in all decent browsers.
When trying it out in IE11 or EDGE this happens:
1. click to select file
2. nothing happens
3. click to select file again -> triggers the `onDrop` callback with no file.

Only way i manage to makes things work is to omit the `accept` prop.

**Comment by ganapativs** [comment]
+1

**Comment by okonet** [comment]
Is this related to the browser? Can you try reproduce it without this module and react?

**Comment by okonet** [comment]
Is this related to https://github.com/okonet/react-dropzone/issues/241?

**Comment by andschdk** [comment]
I guess it could be related but not sure.

Found a pen and quickly modified it to use `accept="text/csv"`.
Check it out here: http://codepen.io/anon/pen/NbGvMw (no react, no dropzone)

In IE `text/csv` does not force you to choose a CSV file. I guess it isn't a valid MIME type. It is supported in decent browsers though.

It looks like it is something with this module 😕

**Comment by okonet** [comment]
How can this be related to this module? We don't do anything fancy with the prop just setting it on the `input` element.

**Comment by Kitanotori** [comment]
It's a platform issue. Same problem with Firefox and Chrome on Windows. react-dropbox needs to do some corrections to the file types provided by browser. Related to https://github.com/okonet/react-dropzone/issues/276

**Comment by abury** [comment]
I'm getting this as well. It's happening with every browser on Windows when trying to select a CSV file.
