### ISSUE TITLE
[Bug report] when opened with click & select files not accepted, files will still be accepted, and rejectedFiles will be []

### ISSUE THREAD

**Issue by alexgzhou** [okonet/react-dropzone#259]

**Comment by okonet** [comment]
How could you select files that aren't comply to `accept` attribute?

**Comment by alexgzhou** [comment]
i can change the file type in the prompt files select window on purpose, although normal users would not do that, anyway it may be not a problem at all in real use cases.

**Comment by okonet** [comment]
It should not be possible. Please report to windows. I'll close it here.

**Comment by alexgzhou** [comment]
![20161022163820](https://cloud.githubusercontent.com/assets/3846121/19618197/feadf04e-9875-11e6-921d-043a0d04082c.png)

it is possible, but you can leave it, barely no one would change the file select filter is real use case.
