### ISSUE TITLE
Invalid push to npm - no dist/ folder

### ISSUE THREAD

**Issue by xswordsx** [okonet/react-dropzone#261]
As of `3.7.1` the directory of the module has:
```
.babelrc            
.editorconfig       
.eslintrc           
.travis.yml         
CHANGELOG.md        
LICENSE             
README.md           
mocha-environment.js
node_modules        
package.json        
src                 
webpack.config.js
```

while `package.json` describes the entry point as `dist/index.js`

**Comment by okonet** [comment]
I'm working on it. Sorry for that.

**Comment by okonet** [comment]
Should be fixed in https://github.com/okonet/react-dropzone/releases/tag/v3.7.2. Sorry for the mess. I was switching to semantic-release and messed a few things up.

**Comment by xswordsx** [comment]
Working - confirmed. Thanks for the quick fix.
