### ISSUE TITLE
on drag over show a div

### ISSUE THREAD

**Issue by artsx** [okonet/react-dropzone#271]
Hello,

Is what it would be possible at on drag over area we did appear a div (like a modal / dialog) instead of just changing the css a border ? 

Thx for any help,

Best regards,

Example (Slack)  
![tetsersss](https://cloud.githubusercontent.com/assets/7711803/20064726/f9008baa-a50b-11e6-9c7c-3a0bb93a77f8.jpg)

**Comment by okonet** [comment]
There are different callback available: https://github.com/okonet/react-dropzone/blob/master/src/index.js#L316 so you can hook in and react to different user actions as you wish. So I believe yes, you can implement anything you want.

**Comment by artsx** [comment]
Can you give me any example ? 
I've do :  
    ```
onDragEnter(){
      return(
        <div className="dropZone">
          <div className="dropZoneContent">
            <h3>DRAG & DROP</h3>
            <p>import your file</p>
          </div>
        </div>
      );
    }
```

But I dont know how bind this function for to have a render with div

**Comment by okonet** [comment]
Sorry, I can't give you an example. You can hire me to implement this though.

Either way, you'll still need to handle global drag events on your own. See #149

**Comment by artsx** [comment]
It's ok, I've found my misstake.
No thank you, I shouldn't pay for help while there are sites like StackOverflow or people to help debug.
Thank you for this wonderful plugin anyway!
