### ISSUE TITLE
id attribute on input

### ISSUE THREAD

**Issue by DanielRuf** [okonet/react-dropzone#274]
If a label is not directly wrapped around the dropzone input but before (eg in another column in a grid), the id can not be set through the id property of the Dropzone component but has to be set to trigger the field.

https://github.com/okonet/react-dropzone/blob/68f39d7f9a7fd16860f93471678e5b96c8954154/src/index.js#L260-L262

Currently we can only set it with inputProps which feels a bit weird but works.

See http://jsbin.com/pizuxelecu

**Comment by okonet** [comment]
It can be set through `inputProps` as you already figured out so I'm closing this as invalid.

If you have a proposition of how to make it better, I'm all ears 👂

**Comment by DanielRuf** [comment]
Right, saw it afterwards but at least it is no consequent to only set the name when we also have to set the id because this is used for labels. I hope you understand my point of view.

But the inputProps way is ok for us.

**Comment by okonet** [comment]
I understand, and `name` should probably go away for consistency reasons.

**Comment by DanielRuf** [comment]
Right. 

Unfortunately `inputProps` was not mentioned in the readme.

Is there some convention to use `inputProps` for these values or where does this come from? Because many React components implement `inputProps` but I find no general documentation about `inputProps` in React.

**Comment by okonet** [comment]
>Unfortunately inputProps was not mentioned in the readme.

You're welcome to submit a PR that fixes that :)

> Is there some convention to use inputProps for these values

No, this is completely custom and made into the project to solves such issues.

**Comment by SengitU** [comment]
Please see #411 for this issue.
