### ISSUE TITLE
MIME type mismatch between platforms

### ISSUE THREAD

**Issue by Kitanotori** [okonet/react-dropzone#276]
**Problem:** file MIME type is not recognized as same across platforms. .csv file in OSX is recognized as _text/csv_, whereas in Windows it is recognized as _application/vnd.ms-excel_.

**Expected behavior:** .csv (and also other file types) are recognized uniformly across platforms, e.g. csv files as _text/csv_, and so on.

Tried with both Chrome and Firefox.

**Comment by okonet** [comment]
I'm not sure about this one since I was hoping to avoid patching browsers in this library. Doing it will also require patching https://github.com/okonet/attr-accept or am I wrong?

Is there even a list of such inconsistencies? Can you point me to it? Do you mind creating a PR that solves this issue?

**Comment by Kepro** [comment]
this should be only problem with Windows... i don't think @okonet  need change something, or just add some documentation for watch about that :)

**Comment by okonet** [comment]
I think documentation PR would also be helpful!

**Comment by okonet** [comment]
@Kepro @Kitanotori any news on the documentation PR? If you're about to do it, please do it against this branch: https://github.com/okonet/react-dropzone/tree/styleguide

**Comment by erinknight242** [comment]
I am seeing this issue as well; I have mine set to accept: "text/csv, application/vnd.ms-excel", which works fine for drag/drop, but when I open the file browser, it is preset to the type "Microsoft Excel 97-2003 Worksheet", which shows no matching items in the selected folder (that _does_ have csv items), making the user change the file type to "All Files" to see the available items. Would love to avoid this extra step, and have it automatically be on "All Files", is that possible?

**Comment by philippfrank** [comment]
@okonet I'd be happy to enhance the docs about that. What are *the docs*. `README`? `gh-pages` branch?

**Comment by okonet** [comment]
@philippfrank docs are now in `README` and I'm working on the new styleguide ATM here: https://github.com/okonet/react-dropzone/pull/313 so you probably want to contribute to it.

**Comment by philippfrank** [comment]
It turns out that IE Edge (WIN10, fresh VM from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) won't set a mime type at all. `file.type` is just an empty string and dropped files are rejected. 

`accepts="text/*,"` (note the comma) is a workaround but it would be nice if one could provide a custom function which can be used to perform additional checks, e.g. whether the file extension is `csv`.

**Comment by flybayer** [comment]
I'm seeing the same thing as @philippfrank in Electron (Chrome) on Win10 VM. No MIME type at all 😢

**Comment by rodrigc** [comment]
@okonet just for my knowledge, how does drop zone determine the mime type?  Is it calling some OS specific function?

Thanks.

**Comment by okonet** [comment]
@rodrigc It doesn't. Not sure what's your question is about.

**Comment by irae** [comment]
@flybayer Electron does not count as Chrome. They have same rendering engine (roughly, but this kind of rich information with OS interactions is precisely the portions Electron don't re-use from Chromium). Electron is a very active project, I bet you can file a bug for them to take a look, or even file a PR if you have the time to fix it yourself.

**Comment by okonet** [comment]
I'm not sure this issue can be tackled right now. I realize this can be very annoying but it seems impossible to fix at this moment. If anyone have a suggestion — feel free to create a PR.

**Comment by srikanth-pmap** [comment]
for .doc, .docx i am not able to get the file type, in the file object returned from the dropzone i'm getting file type as empty (type="")
![15-6-17 am 11-24-54](https://user-images.githubusercontent.com/16321079/27167417-57314bb0-51be-11e7-8deb-f22768259dcb.png)

**Comment by readeral** [comment]
Glad to see you're on this - bit of a bummer to see it's at a roadblock.

Some cursory reading indicates this will continue to be a pain long term, due to what MIME types are typically used for (["Browsers often use the MIME-type to determine what default action to do when a resource is fetched."](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types)) and Windows will always want to drive toward their own applications. I think the best we can do is develop a list of all valid MIME entries for each platform, maybe a whole new project that can be an optional dependency in react-dropzone for smoothing over these issues. I agree that patching browser/platform issues should be kept out of this library.

**Comment by Ondoher** [comment]
There needs to be a solution to this, maybe a generic wildcard that will accept anything, or a file extension check. This just does not work on Windows with .json files. 

My only solution may be to rewrite an entire chunk of functionality, or fork the repository.

**Comment by okonet** [comment]
@Ondoher if you have a proposal for a robust and lightweight solution, I'm all ears. I think https://github.com/jshttp/mime-db has all the needed information but bundling this amount of code to the client app is just too much IMO.

**Comment by Ondoher** [comment]
Let me try this another way. You have written software that fails to work properly on a common platform. This is something that you should care about and try to fix. Or at least provide the tools to put the caller in control of validation.

**Comment by okonet** [comment]
@Ondoher first of all, I won't tolerate the demanding tone in this repository. You can demand something if you pay for it. This repository, although, says explicitly that everything provided here is for free and you're use it on your own risk. See the license file.

> You have written software that fails to work properly on a common platform. 
> This is something that you should care about and try to fix.

I don't think you understand how open source works. If it doesn't fit your needs, then don't use it. If you have a solution to this problem, then create a PR and we'll discuss it.

> Or at least provide the tools to put the caller in control of validation.

https://react-dropzone.js.org/#proptypes You can use `onDrop` callback for the validation.

**Comment by Ondoher** [comment]
I understand open source, and I was not trying to be disrespectful, but when your response to a pretty fundamental problem appears to be, "then why don't you fix it," that response is not really helpful. 

I had already looked at your docs, and here is what it says:
"Mime type determination is not reliable accross platforms. CSV files, for example, are reported as text/plain under macOS but as application/vnd.ms-excel under Windows. In some cases there might not be a mime type set at all."

An acknowledgement of the problem is nice, but there is nothing there that tells me how to solve it. 

Now, if I understand what you're saying, rather than responding to onDropAccepted, I instead respond to onDrop, then I can look at both the accepted and rejected file lists, and do my own validation instead, that's a viable solution for me. Not ideal, but viable.

Thank you

**Comment by RXminuS** [comment]
@Ondoher The point of Open Source is to avoid making "Feature Requests" and always make a "Pull Request". Even if it's a crappy implementation, or not finished...or even just inline comments with TODO items in places where you think a fix needs to be added.

It's much easier as a maintainer to comment on the seed of a solution and you'll get a much more positive response. @okonet has done a fantastic job providing a piece of open source code that solves a lot of headaches for a lot of people and your tone (even though probably not intentionally disrespectful) can really demoralise a maintainer. 

Being a maintainer doesn't mean that you're a Q&A and code-for-free service. So he's not responsible for telling you how to fix it...WE are. His job as maintainer is to maintain a vision for the project and engage the community around it, which again I think @okonet has done a fantastic job at (as evidenced by 3k stars).

Sorry for hijacking the thread like this but it just really upset me too.

**Comment by rodrigc** [comment]
I did some debugging using the Javascript debugger in the Chrome browser, and learned the following.   When doing a file upload, `okonet/react-dropzone` gets an event from the browser, which gives it a `File` object:  https://developer.mozilla.org/en-US/docs/Web/API/File

The `File.type` member of this object should be populated, but in some cases on Windows, it is empty.

It is the responsibility of the browser to populate this value, and `okonet/react-dropzone` just takes whatever the browser gives it.   The question is why is this behavior differing on Windows?

I would need to look in the browser's source code to verify how this works.
This StackOverflow article has a good description for how browsers on Windows determine
the mime type:

https://stackoverflow.com/questions/1201945/how-is-mime-type-of-an-uploaded-file-determined-by-browser

On Windows, there is a combination of looking up a hardcoded list,
and also looking in the registry to determine the mime type.

**Comment by Ondoher** [comment]
Yes, windows is just plain messed up in this respect. It does a poor job matching file extensions to mime types. You can edit the registry to make it work, but this is obviously not a practical solution. To solve my problem I just stopped using that event to validate the file type.

**Comment by rodrigc** [comment]
@srikanth-pmap I bet you don't have Microsoft Word installed on your system, which is why uploading a file with *.doc* or *.docx* extension returned an empty value for *File.type*.

I would suggest that you look in the registry for *HKEY_CLASSES_ROOT\.doc* and *HKEY_CLASSES_ROOT\.docx*, and see if there is a value for *Content Type*.

If you are able, install Microsoft Word, and then look at those registry values again.

**Comment by leonardopavanello** [comment]
Hello, this is closed by I have the similar issue thatn @Ondoher. 
Maybe the Dropzone could accept a new prop to allow a custom acceptFile function "acceptFileValidator" or "acceptFileChecker"

**Comment by Nithendra** [comment]
HI, i am trying to upload ".tab" file but it is not allowing me.

**Comment by Nithendra** [comment]
can i upload some custom file extension if yes please share you knowledge

**Comment by export-mike** [comment]
Yeah I now have a basic check for the extension.

Pseudo code:

```js
< ... accept="" onDrop={file => {
 if(!file.name.endsWith('.csv')) { this.setState({ rejected: true }) }
 // doSomething();
} >

```

**Comment by BalaSudheer** [comment]
I could able to fix this issue with below piece of code. So that the Content-Type will be set properly. 

data.append('file', new Blob([fileData], { type: 'text/csv' }));

**Comment by akfaisel** [comment]
Isn't this solved yet? I'm having the same issue with v5.7.0

But I'm temporarily using .doc,.docx in acceptedFiles to fix this issue. I still cannot use application/msword

acceptedFiles: '.doc,.docx'

**Comment by BartoszLobejko** [comment]
This is how I solved the problem. I'm using Formik with Yup

```javascript
<TrbInputDropZone
            id='financeFile'
            required
            labels={labels.form.dropzone}
            accept='text/*, application/vnd.ms-excel'
            multiple={false}
          />
```

the relevant part of the above component

```javascript
const onDropAccepted = useCallback(
    files => {
      const file = files[0];
      if (file) {
        setFieldValue(`${id}Object`, file);
        const reader = new FileReader();
        reader.onload = () => reader.result && setFieldValue(`${id}String`, reader.result);
        reader.readAsText(file);
      }
    },
    [id, setFieldValue],
  );

  const onDropRejected = useCallback(
    files => {
      const file = files[0];
      if (file) {
        setFieldValue(`${id}Object`, file);
      }
    },
    [id, setFieldValue],
  );

setValidationSchema(prevState => ({
      ...prevState,
      [id]: Yup.mixed(),
      [`${id}Object`]: Yup.mixed()
        .required('Required')
        .test('fileSize', labels.error, value => value && value.size <= OTHER.file.maxSize)
        .test('fileFormat', labels.error, value => value && value.name.search(/\.csv+$/i) !== -1),
    }));
```

**Comment by royk** [comment]
Seems like `application/vnd.ms-outlook` (.msg) has the sample problem on Windows.

**Comment by AlexMCarv** [comment]
.xls, and .ppt files using Chrome on macOS are also grayed out. Even when using the correct mime type: `application/vnd.ms-excel.`, `application/vnd.ms-powerpoint`. Funny how .doc works fine. Is this a Chrome issue?

**Comment by jawwwr** [comment]
I am also having a problem with .zip files on windows, it's returning an empty array but it works well on OSX.

**Comment by luis-martins-ti** [comment]
> for .doc, .docx i am not able to get the file type, in the file object returned from the dropzone i'm getting file type as empty (type="")
> ![15-6-17 am 11-24-54](https://user-images.githubusercontent.com/16321079/27167417-57314bb0-51be-11e7-8deb-f22768259dcb.png)
> And when i give mime-type extension ("application/msword") of .doc type to "accept" parameter of drop zone, it was not accepting .doc type files.


A solution for empty or incompatible Mime-Types would be to convert the file to the blob type, check the file extension, add the corresponding type to the blob and convert the blob to file again.

A example Solution from my friend Eduardo Carvalho (https://github.com/duhwcarvalho):

//input file
<input  type="file" onChange={ onFilesAdded }/>


//receive file or multiples files from input file
function onFilesAdded({ target: { files }}) {

  foreach(files as file) {

    if (file.type === "") {
      //Get file extension from file name
      const split_name = file.name.split('.');
      const type = split_name[split_name.length - 1];

      //create a blob from file
      const blob = new Blob([file], { type: mimeType(type) });

      //Here you can use the file as you wish
      new_file = blobToFile(blob, file.name);
      console.log(new_file);

      formData.append(props.formDataFileString, blobToFile(blob, file.name), file.name);
    } 

  };
}


// Check mimeType By extension - Excel files check only
function mimeType(extension) {
  switch (extension) {
    case 'xlsx':
      return 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';

    case 'xls':
      return 'application/vnd.ms-excel';

    default:
      return 'text/*';
  };
};


//Convert Blob to File again
function blobToFile(theBlob, fileName){
  theBlob.lastModifiedDate = new Date();
  theBlob.name = fileName;
  return theBlob;
};

**Comment by theutkarshsoni** [comment]
Thanks @luis-martins-ti for the solution. I was stuck from 1 week on this. You saved me.

**Comment by krnlde** [comment]
> whereas in Windows it is recognized as _application/vnd.ms-excel_.

only if you have Office installed, otherwise you'll get an empty mime type.

**Comment by mymoto23** [comment]
has anyone identified specific replication steps to this problem?

I'm currently on react-dropzone v11.7.1, and one of my clients have experienced the issue on Windows 10, Chrome 105.

Our team has received the file that's causing the error and tried it on our end, but it seems to be working fine (win 10 and chrome 105 is as specific as we can get as to how identical our environment is)

One of my suspicion is the version of Windows (Pro, Home, etc.), which popped up in my head after reading some of the threads mentioning the browser searches the registry, but I'm not sure if the OS matters, or the version.

**Comment by martin-neotech** [comment]
> Deprecated: This feature is no longer recommended.

https://developer.mozilla.org/en-US/docs/Web/API/MimeType
