### ISSUE TITLE
Get dropzone ref on drop 

### ISSUE THREAD

**Issue by soundwire** [okonet/react-dropzone#280]
When implementing multiple dropzone components, how can we capture the reference (be it a "ref", "name" or any identifying attribute) of the component which was just used to perform the upload?

Although a "solution" to this can be to bind the onDrop function for each component separately, i.e.
`<Dropzone onDrop={this.onDrop.bind(this, param)}></Dropzone>`
it prevents one from binding the function globally (in the React.Component constructor) and possibly introduces performance issues.

Is there a different recommended solution to this?

**Comment by okonet** [comment]
No, there is no other recommendation as to use top-down approach. This is the idiomatic React and you should not rely on children in your component.

I wouldn't care about perf issues in this case until you confirm you have some because of the `bind`.

Using `ref` will get you access to DOM node but this is not what you're looking for either way.

**Comment by soundwire** [comment]
Thanks @okonet, 
Just to clarify that my objective is to collect the data from a large form (including multiple dropzone fields) when it submits.

I am not looking to access the DOM in order to perform something, 
but rather to have a nicely organized object with all the data captured from each field in the form.

**Comment by okonet** [comment]
Yes, I understand that. And therefore in React you have `this.state` that you can modify when `onDrop` occurs.

**Comment by soundwire** [comment]
From the examples i've seen the dropped files are handled under a single property inside state
i.e. `this.state = { files: [] }`. 
I didn't find an example of having `this.state = { dropzone1: [], dropzone2: [], etc.`

**Comment by okonet** [comment]
That's because there is no such example.
