### ISSUE TITLE
Obtain FileList instance

### ISSUE THREAD

**Issue by sandervanhooft** [okonet/react-dropzone#298]
How can I obtain a [FileList](https://developer.mozilla.org/en-US/docs/Web/API/FileList) instance with the uploaded files?

I read [here](https://github.com/okonet/react-dropzone/pull/10) that react-dropzone now yields an array of Files now instead.

Another library I'm using however requires a FileInput and cannot handle an array of Files. It seems impossible to me to convert an array of Files back to a FileList.

**Comment by okonet** [comment]
It looks like the `onDrop` callback will be called with the `event` instance as an argument as well: https://github.com/okonet/react-dropzone/blob/master/src/index.js#L127 

You can obtain the FileList instance from it I guess.

**Comment by sandervanhooft** [comment]
@okonet Thanks for that suggestion.

That parameter returns a `Proxy` object (logged to console). Any clue how to process that into a `FileList` object?

**Comment by okonet** [comment]
AFAIK React uses `Proxy` only in Dev mode. Use same way you would do with normal `Event` object: `event.dataTransfer`
