### ISSUE TITLE
Feature: add paste from clipboard

### ISSUE THREAD

**Issue by jcalfee** [okonet/react-dropzone#299]

**Comment by kof** [comment]
Probably out of scope for the dropzone.

**Comment by okonet** [comment]
@jcalfee thank you for your feedback!

I also think it's out of the scope of this library and thanks to React's composition is easily done in userland. 

I also think that a feature like this will raise the complexity of the project. For example, if you have multiple dropzones on screen, which one should react to the `onPaste` event?

**Comment by jpdevries** [comment]
Could maybe make the dropzones focusable by keyboard and only the currently focused one responds to the event

**Comment by okonet** [comment]
@jpdevries see my previous comment:

> I also think it's out of the scope of this library and thanks to React's composition is easily done in userland.
