### ISSUE TITLE
Accepting drop partially

### ISSUE THREAD

**Issue by kof** [okonet/react-dropzone#307]
If a user drops multiple files, one of them is too big (maxSize) and one is ok, onDropAccepted should be fired with the accepted file.

The fix is very trivial, its just removing   `else` in  `} else if (acceptedFiles.length > 0) {`

**Comment by okonet** [comment]
Thanks! Mind creating a PR?

**Comment by kof** [comment]
sure

**Comment by okonet** [comment]
Please wait until I'll merge new tests branch so you can add the test case. Switching to enzyme.

**Comment by kof** [comment]
👍
