### ISSUE TITLE
Enhancement ideas

### ISSUE THREAD

**Issue by paramaggarwal** [okonet/react-dropzone#31]
As this project is picking up steam, lets plan where we should take it next.

[Updated items as per suggestions in the comments below]

- [x] Add tests
- [x] `disabled` state

**Comment by wmartins** [comment]
I've been using this project for a while, and here are some things I'm missing:

- Build instructions missing (there's any build scripts / build instructions to help people contribute with the project)
- Demo not updated (the last update was in Feb 9)
- Disabled state
- Tests (as you said)
- Browser compatiblity

That's it :-)

**Comment by paramaggarwal** [comment]
Going to create separate issues for each of these, and will leave this particular issue open for further suggestions.

**Comment by wmartins** [comment]
@paramaggarwal, I think it's better to have both, add `disabled` to the input and maybe add some basic styles (some classes are enough) to represent the disabled state. What do you think?

**Comment by mmmurf** [comment]
also perhaps have it respond to a tap on mobile to open the file dialog.

**Comment by eventhough** [comment]
@paramaggarwal can we add support to detect when a file is hovering over the dropzone? It would make it easier to add an effect.

**Comment by lancetw** [comment]
Please support mobile :+1:

**Comment by django-emerge** [comment]
mobile please!

**Comment by paramaggarwal** [comment]
Well there would be no concept of drag and drop on a mobile, folks! If you'd like file inputs on mobile, you can simply use an `input` field!

**Comment by django-emerge** [comment]
Fair point.  I guess what I really want on mobile is a working file uploader that's easily styled and includes previews.  Which is probably at odds with the intention of dropzone/this lib.

**Comment by faergeek** [comment]
What about having a callback which filters out unaccepted files?

**Comment by SylarRuby** [comment]
Delete button for uploaded files (can be added easily no problem). React complains about `key` when file(s) uploaded.

**Comment by okonet** [comment]
@SylarRuby file a `key` issues as a separate issue. Delete button should be done in userland. This library allows you to put any content you want in it.

**Comment by SylarRuby** [comment]
@okonet Thanks

**Comment by okonet** [comment]
I'm closing this one. Seems all mentioned enhancements are implemented already. For new stuff please file separated issues with `enhancement` label.
