### ISSUE TITLE
Passing more than 1 parameter to onDrop

### ISSUE THREAD

**Issue by mfgabriel92** [okonet/react-dropzone#310]
Hi,

Is there a way to accept 2 or more parameters in the `onDrop` method? I need to also pass an `id` from the current row of the table.

**Comment by okonet** [comment]
You're passing a function that you own. Just make this function accept all needed parameters.

**Comment by vandiced** [comment]
This is closed but the only answer is "You're passing a function that you own. Just make this function accept all needed parameters." - can you give a code sample? If I pass a parameter to my "function that I own" for the onDrop event it overwrites the 'files' parameter with my parameter and this is a no no....

**Comment by okonet** [comment]
Here is an example:

```js
<Dropzone onDrop={(accepted, rejected) => {this.onDrop(accepted, rejected, 'third')}}>
  <p>Drop files here...</p>
</Dropzone>
```

and your function could look like

```js
onDrop(accepted, rejected, myArgument) {
  console.log(accepted, rejected, myArgument)
}
```

Hope that helps.

**Comment by elebumm** [comment]
For the hook, it's something similar:

```javascript
useDropzone({ onDrop: (droppedFiles) => onDrop(droppedFiles, files) });
```

**Comment by lalit7788** [comment]
@elebumm, I am using the hook but unable to pass a second parameter to the onDrop. The `useDropzone` being a hook is declared at the top but the parameter I wish to pass (a column id) is only available inside an Array.map() call inside the render block.

Do you have an idea how I can achieve my goal?

**Comment by jacktsin1** [comment]
@lalit7788 Had exactly the same issue. Your comment is the solution, GJ!!

**Comment by devcoderbuzz** [comment]
@lalit7788  for me  i am getting the second param emtpy array. tried to pass string but still no luck

**Comment by lalit7788** [comment]
@devcoderbuzz, have you found a solution to your issue? If not then seeing some of that code of yours would be nice.

**Comment by devcoderbuzz** [comment]
> @devcoderbuzz, have you found a solution to your issue? If not then seeing some of that code of yours would be nice.

Thanks, i found the solution.
