### ISSUE TITLE
can't accept m4a files on safari when `accept` attribute set to `audio/*`

### ISSUE THREAD

**Issue by westlinkin** [okonet/react-dropzone#314]
This only happens on safari, chrome & firefox works fine.

Any ideas?

**Comment by okonet** [comment]
Please add steps to reproduce since it's unclear what part isn't working. But afaik there are some inconsistencies in browsers regarding `accept` behavior.

**Comment by westlinkin** [comment]
Sorry, I found the solution, just set `accept` to `audio/x-m4a, audio/*` instead of `audio/*`, safari on mac can accept m4a files
