### ISSUE TITLE
Unable to get filename or file body for vCard files with react-dropzone

### ISSUE THREAD

**Issue by ewittle** [okonet/react-dropzone#315]
Trying to set up a react-dropzone component to accept vCard files. Here's the component declaration with JSX:
```
<Dropzone onDrop={this.onContactDrop} onDropAccepted={this.onDropAccepted} onDropRejected={this.onDropRejected} accept="text/vcard">
              <p>Drop a contact</p>
            </Dropzone>
```

When I run this, and drag a vCard file into the drop zone, I see onDrop being called as well as onDropAccepted. However, the accepted files array does not include the path to the file nor the body of the file text. And therefore it seems to be useless. I have a console.log statement showing the first element of the array provided to onDrop:

`    console.log('onDrop files[0]', files[0])`

 And what I see in the browser console is:

`onDrop files[0] File { preview: "blob:http://eric.ourlifestories.loc…", name: "Test.vcf", lastModified: 1482930969000, lastModifiedDate: Date 2016-12-28T13:16:09.000Z, webkitRelativePath: "", size: 137092, type: "text/vcard" }`

Since I get the file name, if webkitRelativePath was useful, I would expect to be able to read the file locally. As it is, I cannot understand how I could read the file. This behavior is on MacOS Sierra using both the current version of Firefox and Safari, so it doesn't seem to be specific to a single browser. Any help you can provide would be appreciated.

**Comment by ewittle** [comment]
Never mind, I passed the received file object into a reader, and it works. Apparently ignorance on my part on how the HTML drag and drop interface functions. I got thrown off that there is nothing in the console.log output that appears to provide a way to read the file.

**Comment by tarim** [comment]
Hi @ewittle ,

I have same issue here,  I try to submit(blob parts only) via form(redux form). But, I cannot get it. can you help me please?

Thanks,

**Comment by ewittle** [comment]
You would need to provide more details on what you're trying to do, what your code looks like, and what issues you're seeing.

**Comment by MidnightP** [comment]
Looks like [this](https://stackoverflow.com/questions/40252955/how-to-only-dispatch-filelist-from-datatransfer-after-file-items-are-loaded/41228383#41228383) is the same issue

**Comment by MidnightP** [comment]
@ewittle I am attempting to read the dropped file with a FileReader before placing it in the redux store and sending it to the server. However, the events on the reader never trigger and I can't find out why not. Hope you can help.

```javascript
file // received in my onDrop handler of the react-dropzone component

file instanceof Blob === true
file instanceof File === true

var reader = new FileReader()

reader.onLoad((res) => {
	console.log(res)
})

reader.readAsText(blob)
```

Looking at the documentation and many posts on stackoverflow, this should be right.
The reader indeed changes to `{ readyState: 1, result: "" }` but does never continue to readyState 2 nor does it ever trigger any events.
