### ISSUE TITLE
Cant preview a video

### ISSUE THREAD

**Issue by thomasparsons** [okonet/react-dropzone#318]
As of the latest update, and specifically this line: 

https://github.com/okonet/react-dropzone/commit/0e1645936fa250e5838c09204aff67bf0ee46173#diff-1fdf421c05c1140f6d71444ea2b27638R104

I can no longer use the preview of uploaded videos, only images. I can't seem to see an issue where this was requested, though I do understand the file size might impact it

realistically, I'm not sure allowing a 'disablePreview' option, and then automatically turning them off for anything but images is the best - perhaps just the the `disablePreview` would suffice

**Comment by okonet** [comment]
I wasn't aware you can generate a preview for video files. This can be probably rewritten in a more supportive way. You're probably right about the `disablePreview` that this should be decided upon this.

Do you mind creating a PR that will remove the second check?

**Comment by mkuipers** [comment]
The preview attribute used to be available for all types of files. By rolling back to 3.6.0, I was able to regain the preview functionality, but it would be nice if in future versions we could have the functionality back.

**Comment by ma2web** [comment]
if you use `URL.createObjectURL(file)` and pass this to your src video tag will work
