### ISSUE TITLE
Pass the reject reason to rejected files

### ISSUE THREAD

**Issue by aight8** [okonet/react-dropzone#319]
It's a small thing but it would be just very nice.
Pass somehow the reason why a file is rejected - because of file size or mime mismatch.
Instead of implement the same comparison logic again in custom code, why not just add the reason in the callback.

**Comment by okonet** [comment]
There is #257 but I somehow think it's too coupled with the implementation. I would like to see a better proposal. Any ideas? Let's discuss in the PR.

**Comment by okonet** [comment]
Based on a discussion in #321 I'm closing this one.
