### ISSUE TITLE
Link broken in docs

### ISSUE THREAD

**Issue by nealoke** [okonet/react-dropzone#323]
The docs link for **input element specification** is broken en returns a 404

**Comment by okonet** [comment]
You're welcome to submit a PR that fixes it!

**Comment by nealoke** [comment]
@okonet I would, but really have no idea how it works, even when clicking on pull request 🌵 . I am a developer trust me...

**Comment by nealoke** [comment]
For peeps wanting it now: [input element types](http://www.iana.org/assignments/media-types/media-types.xhtml#image)
