### ISSUE TITLE
Confirm before onDrop handles the files

### ISSUE THREAD

**Issue by kandros** [okonet/react-dropzone#324]
It would be useful to have a function that fires before onDrop

use case: Already have a file in the dropzone want confirmation from the user before override it with another file

**Comment by okonet** [comment]
Related to #321

**Comment by okonet** [comment]
Since you won't have the full information about your files before you drop them, this feature should be implemented in the `onDrop` callback as well.

The implementation is up to you but I imagine it's pretty straightforward since you're dealing with your own state.
