### ISSUE TITLE
Typescript runtime issues

### ISSUE THREAD

**Issue by tarr11** [okonet/react-dropzone#328]
When I embed this using in an ES6 JSX file, this works fine.   I am using Webpack 1 and Typescript.

However, using TypeScript, I get this error (at runtime):
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `Test`.
```

This is my Test component:
```
import * as React from 'react';
import { render } from 'react-dom';
import Dropzone from 'react-dropzone';
interface TestProps {

}
export default class Test extends React.Component<TestProps, {}> {

  render(){
    return(
       <Dropzone onDrop={() => console.log("drop")}>
              <div>Try dropping some files here, or click to select files to upload.</div>
        </Dropzone>
    )
  }

```

**Comment by tarr11** [comment]
This fixed it. 
```
import * as Dropzone from 'react-dropzone';
```

**Comment by ashok-sc** [comment]
This is weird. I had the opposite problem. When I used `import * as Dropzone from 'react-dropzone';` I got that runtime error. Using `import Dropzone from 'react-dropzone';` fixes it though.

**Comment by dupski** [comment]
We've also come across an issue in this area today.

To get our tests running in Node with ts-jest (Jest & typescript), we have to use:

`import * as Dropzone from 'react-dropzone':`

However when that code is built with webpack (v2 currently), we have to use `Dropzone.default` client-side to get a reference to the actual component.

We currently do not use @types/react-dropzone. I'm going to give that a shot later this week and will report back if that helps :)

**Comment by tarr11** [comment]
If you are using `module: 'esnext'` in tsconfig, then you can use `import Dropzone from 'react-dropzone';`

**Comment by asaarnak** [comment]
With get the runtime error with: `import * as Dropzone from 'react-dropzone';`
And compiler error with: `import Dropzone from 'react-dropzone';`
`"allowSyntheticDefaultImports": true,` fixes compiler error, but we use false
```json
"typescript": "2.5.3",
"@types/react-dropzone": "4.1.0",
"react-dropzone": "4.2.1",
```

**Comment by ashok-sc** [comment]
This is coming to bite us now as our production environment because our prod env doesn't like the `import * as Dropzone from 'react-dropzone';` import. The way we're solving this is by removing all the type definitions. @asaarnak you're right that the type definitions are broken. Please someone help.

**Comment by Southclaws** [comment]
Getting this too now, if I `import * as Dropzone from "react-dropzone";` then React complains about `Dropzone` as a function is not valid as a react component. If I try any other combination of import methods, I just get compile errors (import {Dropzone}, import ..., import Dropzone, etc...)

Is there any quick workaround? What was the last working version?

**Comment by ashok-sc** [comment]
The work around is to get rid of the type definitions and use `import Dropzone from 'react-dropzone';`. This is how we got it to work for now. It's not ideal.

**Comment by jurosh** [comment]
Hi guys, shuldn't be this reopened ? looks like there is still issue - or you get it working without workaround ?
@ashok-sc that would probably work, but just with not strictly configured typescript. Otherwise when you delete typings file, you cannot import module without error.

**Comment by goloveychuk** [comment]
@dupski 
solution:
1) make all imports `import * as Dropzone from 'react-dropzone/dist/index';`
2) add react-dropzone.d.ts
[react-dropzone.txt](https://github.com/react-dropzone/react-dropzone/files/1502278/react-dropzone.txt)

This is because 
https://github.com/react-dropzone/react-dropzone/blob/master/package.json#L4-L5
webpack using `module`, typescript `main`. 
In first file we have `export default`, on second - `module.exports = {}`
Why typescript using `main`? I guess because of https://github.com/goloveychuk/ts-jest/blob/master/src/utils.ts#L208-L213
Not 100% sure.

**Comment by YGKtech** [comment]
I'm facing this issue too, the problem has not been resolved and this issue should be reopened.

Currently the only way I've been able to use this in typescript is to not install the `@types` definiton, change my `tsconfig.json` to allow implicit `any` statements, then import it as `import * as Dropzone from 'react-dropzone';` and reference the component as `<Dropzone.default>`

This is a lot of hassle to go through for a single component, and the workaround isn't documented anywhere.

**Comment by rkmarks** [comment]
I'm not sure about the others but I am not familiar enough w/ Typescript to know how to resolve this. If anyone is familiar they can submit a PR referencing this issue.

**Comment by oBusk** [comment]
Workaround for those in desperate need seems to be
 `react-dropzone@4.1.X` and 
`@types/react-dropzone@4.1.X`.

Import as 
```typescript
import * as Dropzone from 'react-dropzone';
```

**Comment by jdcas89** [comment]
This still doesn't work out of the box. Even-though the typings are available from the package. The only thing that worked was what @goloveychuk suggested. This won't work if you have a CI/CD pipeline that install directly from npm. Any suggestions?

**Comment by YGKtech** [comment]
@jdcas89 : only thing that comes to mind would be to ditch the typings and change your tsconfig to allow you to use it as a black box.  I don't even know for sure if that would work, it's just the only thing I can think of off the top of my head for that sort of environment.

**Comment by nickhaughton** [comment]
Still an issue for me.

**Comment by sbaechler** [comment]
@tarr11 Please reopen this issue. It is still not possible to use the library with the provided types in a node environment (such as Jest).

**Comment by rolandjitsu** [comment]
@sbaechler please provide a reproducible example (on codepen, codesandbox, etc.), otherwise we cannot help you. I'm using this lib with Jest and I have no issues.

**Comment by sbaechler** [comment]
@ralic I created a minimal repo and there it actually worked.
https://github.com/sbaechler/react-dropzone-repo

I guess I have to dig deeper into our app and check what we have differently.

**Comment by sbaechler** [comment]
No, there is nothing in the yarn.lock. However, our project configuration is based on react-scripts version 1 while the test repo used version 2.

**Comment by sbaechler** [comment]
So I found the issue: Wepack is importing the module from 'dist/es/index.js' while Jest is importing from 'dist/index.js' since it is a node app. Of course the commonJS module does not have a default export.

If I import directly from 'dist/es' I lose the type definition.

I guess react-app 2 is using a smarter build chain for Jest.

**Comment by rolandjitsu** [comment]
I see, it's possible they do, that might need a bit more investigation though,

**Comment by peraltafederico** [comment]
> @dupski
> solution:
> 
> 1. make all imports `import * as Dropzone from 'react-dropzone/dist/index';`
> 2. add react-dropzone.d.ts
>    [react-dropzone.txt](https://github.com/react-dropzone/react-dropzone/files/1502278/react-dropzone.txt)
> 
> This is because
> https://github.com/react-dropzone/react-dropzone/blob/master/package.json#L4-L5
> webpack using `module`, typescript `main`.
> In first file we have `export default`, on second - `module.exports = {}`
> Why typescript using `main`? I guess because of https://github.com/goloveychuk/ts-jest/blob/master/src/utils.ts#L208-L213
> Not 100% sure.

Hello everyone! I was having this issue when I was using react-dropzone **version ^11.2.0**
```
./node_modules/react-dropzone/dist/es/index.js 
Module not found: Can't resolve 'file-selector
```

And I solved it doing similar steps:

1.- import { useDropzone } from 'react-dropzone/dist/index'

2.-  Add react-dropzone.d.ts with [this content](https://github.com/react-dropzone/react-dropzone/blob/master/typings/react-dropzone.d.ts):


:D
