### ISSUE TITLE
Need the ability to restrict total file size when uploading multiple attachments

### ISSUE THREAD

**Issue by bradbirnbaum** [okonet/react-dropzone#331]
If you select more than one file I would like another prop called `maxTotalSize` that will reject files if it you are uploading multiple and the size exceed the `maxTotalSize`

**Comment by okonet** [comment]
This is your responsibility to implement in the `onDrop` callback. I'll also remove size validation from the upcoming major release so please be aware then upgrading.

**Comment by bradbirnbaum** [comment]
Thanks - that makes sense.   I ended up doing it on my own and also removing our use of `maxSize`
