### ISSUE TITLE
using react-dropzone with import statement

### ISSUE THREAD

**Issue by foobar8675** [okonet/react-dropzone#333]
I'm not sure why this works

`var Dropzone = require('react-dropzone');
`

but this does not?

`import Dropzone from "react-dropzone"`
error
`Uncaught ReferenceError: Dropzone is not defined`

Any thoughts are appreciated.

**Comment by caseychoiniere** [comment]
More info on your setup? I'm importing like `import Dropzone from "react-dropzone"` and it's working fine for me.

**Comment by foobar8675** [comment]
sorry @caseychoiniere , operator error.
