### ISSUE TITLE
upload images in Internet Explorer 11 can't show

### ISSUE THREAD

**Issue by huxubin** [okonet/react-dropzone#334]
upload about 100 images and size about 1~10M in IE11 or IE10 , many of the images can't show !

**Comment by huxubin** [comment]
even if upload 50 images or less , this often happens !

**Comment by okonet** [comment]
This is the browser issue not this library since it uses HTML5 APIs. If you have an idea how to fix this please create a PR.

**Comment by huxubin** [comment]
I try to upload with input file, it fails. As you say this is most likely browser issue not this library. Do you have any fit ployfill to solve this?

**Comment by okonet** [comment]
I don't have anything but I can do a research and work on this case an a paid basis. Write me an email if you're interested.
