### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by okonet** [okonet/react-dropzone#343]
This project needs a logo. I've created 2 versions. If someone has better ideas I'm open to review them as well. For now, I'd say let's vote with 👍  for each variant (that are separate comments).

Inspiration and emoji fallback is 🎯 which I'd like to use on Twitter etc.

**Comment by okonet** [comment]
![logo1](https://cloud.githubusercontent.com/assets/11071/22546842/10ac819c-e93f-11e6-9b80-71c0fc2c4209.png)

**Comment by okonet** [comment]
![logo2](https://cloud.githubusercontent.com/assets/11071/22546846/1692a78a-e93f-11e6-9fb4-d402ac391f31.png)

**Comment by DaZzz** [comment]
One more option 👋 

![dropzone](https://cloud.githubusercontent.com/assets/2707291/22547965/3f1d1c24-e955-11e6-9d5f-a4c580a653d8.png)

**Comment by oliverturner** [comment]
And another...
![react-dnd](https://cloud.githubusercontent.com/assets/21795/22548575/fe78ba4a-e93e-11e6-8f6f-02200d193ba9.png)

**Comment by oliverturner** [comment]
![react-dnd](https://cloud.githubusercontent.com/assets/21795/22548782/0f567464-e940-11e6-9c0f-2a3d5eb0dc97.png)

**Comment by oliverturner** [comment]
![react-dnd](https://cloud.githubusercontent.com/assets/21795/22548937/d4a62c28-e940-11e6-8dfb-2e34d437fc7c.png)

**Comment by okonet** [comment]
@DaZzz and @oliverturner thanks for contributions!

@DaZzz I like it! What I'm not sure about is the pseudo-3d feel of it. Another concern is that it doesn't have no `react` resemblance in it. This is the concern also for my 1st version.

@oliverturner it feels too noisy for me. Too many lines and different perspectives doesn't really help here IMO.

**Comment by oliverturner** [comment]
Fair feedback: I've always seen the React logo as inherently 3D - the lines describing axes of rotation around a nucleus - so I the shift in perspective isn't there for me. I was more about trying to visually integrate a dropzone into the React space.

PS Take your point about the perception of noise, but it has no more lines than yours ;)

**Comment by okonet** [comment]
@oliverturner it's about the number of intersections :)

**Comment by DaZzz** [comment]
@okonet actually react resemblance is what I didn't fully like in second version. Do we really need that? It kinda feels like some sort of react-conf or some new variation of react (like preact, or react-native). Take a look at `react-router` for instance or `react-dnd`. They don't try to use original react logo in any way. I think when you pair your logo with the name of the repo it is already enough. However the logo does tell a bit more about the functionality of the package which I believe a good attribute. 

As for 3d. I think the logo I designed doesn't try too much to appear 3d but this slight detail makes it more finished. Here is the comparison:

![image](https://cloud.githubusercontent.com/assets/2707291/22553147/badd29c8-e96c-11e6-99f2-70fd82eb359a.png)

Although I'm ok with both of them. 😄

**Comment by oliverturner** [comment]
![react-dropzone-redux](https://cloud.githubusercontent.com/assets/21795/22554068/c2d85924-e956-11e6-8ee5-04ef0724c889.png)

couldn't help it...

**Comment by danfernand** [comment]
I love the d letter one or the carrots to the circle. Love the library!

**Comment by DaZzz** [comment]
![dropzone copy 3](https://cloud.githubusercontent.com/assets/2707291/22555588/3018fbba-e975-11e6-9797-8c32a883a32a.png)

**Comment by DaZzz** [comment]
😅 

![dropzone copy 5](https://cloud.githubusercontent.com/assets/2707291/22555679/85d6651a-e975-11e6-9f38-30a7185cf54c.png)

**Comment by okonet** [comment]
I've tried some modifications of @oliverturner and @DaZzz ideas. Thoughts?

**Comment by okonet** [comment]
![logo3](https://cloud.githubusercontent.com/assets/11071/22564995/e87ae9e6-e986-11e6-896f-c9d7ce9318e6.png)

**Comment by okonet** [comment]
![logo4](https://cloud.githubusercontent.com/assets/11071/22564999/ed39c8bc-e986-11e6-8fe7-76cb7f9c9ab3.png)

**Comment by caseychoiniere** [comment]
Not a fan of the "React" logo based design. Cool idea but it looks like an eye. I like the downward arrows into the target design best. And I think @DaZzz version is pretty rad. My $.02

**Comment by oliverturner** [comment]
I'm leaning towards a variant of @DaZzz version myself. Strong work 👍

**Comment by okonet** [comment]
It seems that @DaZzz version is the favorite one. I like it as well and my only concern is that it lacks of "dropzone" sign in it which I'd like to keep. @DaZzz could you try something like https://github.com/okonet/react-dropzone/issues/343#issuecomment-277058556?

**Comment by DaZzz** [comment]
I tried similar approach at first but white pointy angle inside central circle is killing it. Maybe just something like this?

![image](https://cloud.githubusercontent.com/assets/2707291/22601577/95b9dd14-ea50-11e6-88f7-b5d6e655d583.png)

**Comment by kuzminadya** [comment]
Check this please
![screen shot 2017-02-04 at 15 11 36](https://cloud.githubusercontent.com/assets/20212840/22619077/48745dd0-eaec-11e6-9da1-d8831ab61517.png)

**Comment by okonet** [comment]
@kuzminadya this looks too similar to http://www.dropzonejs.com/ and I want to avoid this.

**Comment by okonet** [comment]
@DaZzz I like the original much more. This looks very cartoony for some reason :/ I guess that's because of 3D which I don't really like. How this gonna work with just one color (B&W for example)?

**Comment by okonet** [comment]
Another attempt of stylying the "d" letter:

![logo5](https://cloud.githubusercontent.com/assets/11071/22619365/71ccaab4-eaf3-11e6-8e62-b840c4e1fd73.png)

**Comment by okonet** [comment]
@DaZzz can you provide me with the Sketch / SVG file for your original version? Probably a PR?

**Comment by theodorosploumis** [comment]
Is this issue still active? I could help with this if you like. I am not a professional logo designer but I like creating logos and graphics for open source projects. Should I proceed?

Thanks in advanced!

**Comment by okonet** [comment]
Nope. This can be closed. Thanks!
