### ISSUE TITLE
Support for image URL dropping

### ISSUE THREAD

**Issue by mhelander** [okonet/react-dropzone#349]
I'm proposing enhancement of the drag-drop implementation to accept and handle also image URL's.

This would provide pretty awesome app user experience when all possible scenarios are covered to get images in to the web application.

Of course this is possible to implement by shimming react-dropzone but leads to much of the drag-drop duplication which isn't so practical.

If this proposed feature isn't practical, then supply dropped URL via props method for further handling.

Current 3.9.2 version doesn't support documented onDropRejected method.

**Comment by okonet** [comment]
1. There is an ongoing discussion about allowing only files here #255 
2. If you want to propose an enhancement, please create a PR and we'll discuss it from there.
3. If there are other issues you want to report, create a separate issue for each of them with steps to reproduce and minimal examples.

**Comment by okonet** [comment]
I think this should be implemented as a separate component since it is coupled with the textarea/input by design.
