### ISSUE TITLE
File upload only works on 2nd attempt

### ISSUE THREAD

**Issue by niko-h** [okonet/react-dropzone#351]
Hi,
you examples work for me in part. But it only works on 2nd attempt.
With
>onDrop(acceptedFiles, rejectedFiles) {
    this.setState({ files: acceptedFiles, })

>    console.log('Accepted files: ', this.state.files)
    console.log('Rejected files: ', rejectedFiles)
    this.state.files.map((file) => $('#preview').append('<img src='+file.preview+' />') )
  }

on the 1st attempt, state.files remains unidentified.

Also, this part from the example does exactly nothing. No error, no output.
`{this.state.files.length > 0 ? <div>
                <h2>Uploading {this.state.files.length} files...</h2>
                <div>{this.state.files.map((file) => <img src={file.preview} /> )}</div>
                </div> : null}`

**Comment by okonet** [comment]
`this.setState` is async in React. Try using a second argument which is a callback function to do the work.
