### ISSUE TITLE
How do we resize the square drop area?

### ISSUE THREAD

**Issue by amshim** [okonet/react-dropzone#353]
Looking at src/index.js, it looks like the style is fixed to 200px by 200px. Is there anyway to change that without modifying the package?

**Comment by okonet** [comment]
https://github.com/okonet/react-dropzone/blob/master/README.md#reacting-to-user-input

**Comment by okonet** [comment]
Please note that I'll deprecate `style` and `className` props in next major release in favor of function that returns the component's children (as in README)

**Comment by amshim** [comment]
I still don't quite understand. I want to change how the input box looks even when there is no user input.

If you are deprecating `style` and `className`, how are we supposed to change how it looks?

**Comment by okonet** [comment]
I'll need to pass your styled children to the component.
