### ISSUE TITLE
does not work in ios cordova

### ISSUE THREAD

**Issue by macrozone** [okonet/react-dropzone#354]
On IOS cordova it seems that an automatic click on an input does not work.

However, i found a workaround:

you can lay the `<input type="file" />` above the drop-zone (with position: absolute) and set its opacity to 0 (display: none will not work).

**Comment by alexkerber** [comment]
@macrozone: What do you mean with lay the above? Create a div above the dropzone dz-clickable?

**Comment by macrozone** [comment]
sorry, i forgot a backtick should say: you can lay a `<input type="file" />` above the drop-zone

**Comment by alexkerber** [comment]
Ah awesome @macrozone! Works perfect!

**Comment by alexkerber** [comment]
It just stoped working :/ Someone that have the same issue?
