### ISSUE TITLE
setState does not work onDrop

### ISSUE THREAD

**Issue by abbasfreestyle** [okonet/react-dropzone#355]
For some reason this.setState is not working properly when onDrop is called. Here is my code:

```
class App extends Component {

constructor(props){
    super(props);
    this.state= { files: [] };
  }

  onDrop(accepted, rejected){
      this.setState({files: accepted});
      console.log('accepted: '+this.state.files);
      console.log('rejected: '+rejected);
  }

  render() {
    return (
      <div className="App">
        <Dropzone onDrop={this.onDrop}>
          <div>Upload some stuff here </div>
        </Dropzone>
        {this.state.files.length > 0 ? <div>
                <h2>Uploading {this.state.files.length} files...</h2>
                <div>{this.state.files.map((file) => <img src={file.preview} /> )}</div>
                </div> : null}
      </div>
    );
  }
}
```

1st time i add a file `onDrop()` outputs this.state.files as undefined .
the 2nd time i add a file, `onDrop()` outputs this.state.files as the previous file uploaded.
If i log output this.state.files from another function, this.state.files is ALWAYS empty, even though onDrop() calls the previous result.

This sounds like a bug to me. I've tried `this.onDrop.bind(this)`. This also will never update the actual state.

it seems that the state inside onDrop is separate to the state inside the main app.

I know that setState is asynchronous. But that's meaningless when it's not updating the actual state.

Very frustrating.

**Comment by okonet** [comment]
Here is the working example: https://github.com/okonet/react-dropzone/tree/styleguide/examples/Basic

> I've tried this.onDrop.bind(this)

This should fix your problems.

**Comment by abbasfreestyle** [comment]
Thanks @okonet but this isn't working.

The states are being passed through into `onDrop()` with bind. But `setState` does not update the actual state.

`this.state.files` in `render()` is still unchanged and still remains empty no matter how many times i add a file.

But weirdly `this.state.files` show the previous file data INSIDE `onDrop()` function only

**Comment by okonet** [comment]
the example I sent you is working. So it must be something with your code. Try to debug a minimal use case.

**Comment by abbasfreestyle** [comment]
Thanks @okonet 

I've tried it again today and for some reason it's decided to work. I've implemented the bind, using the exact same code that failed the other day.

I think it might be a react issue, I know the code should have worked that day and now it's working today. Very strange!

Thanks for your help. It's working, so closing issue.

**Comment by xxtanisxx** [comment]
I'm getting this issue too. If I were to upload one file at a time, the state will not update. If I were to upload one file then two files, then the state will update. It is weird.

**Comment by itsashis4u** [comment]
This may be because of `setState` being async in nature, you can use callbacks in `setState`

**Comment by d-adamkiewicz** [comment]
It's the same weird behaviour as described in origin post, code is using `useState()` hook.
`the state` ie `listOfFiles` holds empty array on first drop, and on second drop has data of previously dropped file, etc

```javascript
import React, {useState} from "react";
import Dropzone from "react-dropzone";

function App() {
  const [listOfFiles, setListOfFiles] = useState({files: []});
  const onDrop = files => {
  setListOfFiles({files});
/*
1.png {files: Array(1)}
1.png {files: Array(0)}
*/
   console.log(files.map(f=>{return f.name}).join(''), {files});
   console.log(files.map(f=>{return f.name}).join(''), listOfFiles);
  };

  const files = listOfFiles.files.map(file => (
    <li key={file.name} style={file.style}>
      {file.name} - {file.size} bytes
    </li>
  ));

  return (
    <Dropzone onDrop={onDrop}>
      {({getRootProps, getInputProps}) => (
        <section className="container">
          <div {...getRootProps({className: "dropzone"})}>
            <input {...getInputProps()} />
            <p>Drag 'n' drop some files here, or click to select files</p>
          </div>
          <aside>
            <h4>Files</h4>
            <ul>{files}</ul>
          </aside>
        </section>
      )}
    </Dropzone>
  );
}

export default App;
```

**Comment by BhawnaBatra** [comment]
Hi @d-adamkiewicz ,
I am also getting the same issue. Did you find any solution?
Thanks in advance.

**Comment by itsashis4u** [comment]
This is because you expect setListOfFiles({files})  to be syncronous. But it is not.
You can use `useEffect` to get the dropped files
