### ISSUE TITLE
Allow custom message for mixed file-types, while still dragging

### ISSUE THREAD

**Issue by femesq** [okonet/react-dropzone#356]
I want to propose a PR that allows us to display more information to the user, while still dragging:

```
class Dropzone extends React.Component {
  static renderChildren(children, isDragActive, isDragReject, filesAccepted, filesReject) {
    if (typeof children === 'function') {
      return children({ isDragActive, isDragReject, filesAccepted, filesReject });
    }
    return children;
  }
  ....
}
```

Since we can drop both allowed and disallowed files all together (and `onDrop` already handles this), with the suggestion I'm proposing, we could tell the user some extra info, before he drops the files...

May I spend some time on this, or it would be considered out of the scope of the project?

Thanks,

**Comment by okonet** [comment]
Hmmm. After some thought I even think that passing the whole dropzone' state to children isn't that bad idea after all. Will it solve this use case as well?

**Comment by femesq** [comment]
Not sure if I've got your idea, since now we only have `{isDragActive, isDragReject}` on DropZone's state...

But if you meant to include other vars (available on `onDrop` method), I think it would solve:

```javascript
onDrop(e) {
    const { onDrop, onDropAccepted, onDropRejected, multiple, disablePreview } = this.props;
    const fileList = getDataTransferItems(e, multiple);
    const acceptedFiles = [];
    const rejectedFiles = [];

    // ...... keep everything else....

    // Reset drag state
    this.setState({
      isDragActive: false,
      isDragReject: false,
      acceptedFiles: acceptedFiles,
      rejectedFiles: rejectedFiles
    });
  }
```

and them:

```javascript
class Dropzone extends React.Component {
  static renderChildren(children, isDragActive, isDragReject) {
    if (typeof children === 'function') {
      return children(...this.state);  //    <= Sending entire state to children
    }
    return children;
  }
``` 


Maybe we could even send `fileAccepted` function down to children, so that we can verify why any file was rejected (file's size ou type):
```javascript
    // Reset drag state
    this.setState({
      isDragActive: false,
      isDragReject: false,
      acceptedFiles: acceptedFiles,
      rejectedFiles: rejectedFiles,
      fileAccepted: this. fileAccepted,
      fileMatchSize: this. fileMatchSize
    });
``` 

PS.: After writing this, it seens too over... I wouldn't mind re-writing those one-line-function again... Kind of too much specific use-case...

**Comment by okonet** [comment]
Hmm, how will you make the `fileAccepted` and `fileRejected` available during the drag? These can only be obtain in `onDrop` method...

**Comment by femesq** [comment]
😔
You are right... I haven't made the tests before proposing this... Sorry about that..

Reading the code, it made me believe that the `getDataTransferItems` function call on lines [L57](https://github.com/okonet/react-dropzone/blob/master/src/index.js#L57) and [L104](https://github.com/okonet/react-dropzone/blob/master/src/index.js#L104) were equivalents.

Have tested now, and the result are very different (using Chrome@56.0.2924.87).

Now I've got confused... 
What does `getDataTransferItems` on [L57](https://github.com/okonet/react-dropzone/blob/master/src/index.js#L57) do, exactly?

**Comment by okonet** [comment]
Well, it checks if all files are accepted based on `accept` prop. Most of the browsers still provide you with some meta-information on types of the draggable items which is used there.

The `getDataTransferItems` method itself is here to remove some cross-browser inconsistencies.

**Comment by femesq** [comment]
It is interesting, because although I can't debug it in browser's inspector (`DataTransferItemList` has only `length` property, which is 0), it still works (telling me the file I'm dragging is not allowed when it is not). [Chrome]

In Firefox, `DataTransferItem` items on `DataTransferItemList` has more visible properties: 
````javascript
kind:"file",
type:"application/x-moz-file"  /// No matter which kind of file I drag
````
In this case, Firefox rejects files that should be accepted... I checked that `attr-accept` uses the `type` property...

Seens like there is no robust way of achieving this while dragging...
Actually, [this strategy](https://github.com/okonet/react-dropzone/blob/master/src/index.js#L13) can lead to false-negative Rejects..

Does it deserve a note on Docs?

**Comment by okonet** [comment]
Re: Firefox was working as expected before. I'll need to check again.

**Comment by femesq** [comment]
#362

**Comment by oyeanuj** [comment]
@okonet @femesq It seems like to determine `isDragActive`, we are already checking if all the files are going to be accepted which seems very similar to the logic we have in `onDrop`. So, if instead of using `files.every`, we instead use a `files.reduce`, we could very well separate the files being dragged into accepted and rejected. And in terms of browser support, maybe we support it only for browsers that give this information - in which sense it is as reliable as, and as consistent with `isDragActive`.

Do you think it makes sense to pass which files are going to be accepted/rejected (not the ones already accepted/rejected which a user can access from state)? 

In my usecase, I am looking to show the user which of their files are going to be rejected as they drag, even before they drop it.

**Comment by femesq** [comment]
The problem I saw is that we can get false-positive results, as you can see in #362.
For my usecase, that is not possible. Also having cross-browser inconsistency wouldn't be good for my product, so I gave up this pre-drop checking...

**Comment by oyeanuj** [comment]
@femesq Hmm.. it seems that bug mentioned in Firefox in that thread seems to have been fixed in Firefox 53.

Also, if there are other browser quirks other than the Firefox bug, then that would imply that `isDragActive` or `isDragReject` are also unreliable - has that been your experience?

**Comment by femesq** [comment]
I haven't gone much deeper since then..  Neither tested on enough browsers
to confirm a wider problem..

Because of that bug the feature of my product that uses `drop-zone` have
dropped this pre-drop checking... Will try it again soon...

**Comment by okonet** [comment]
I'm closing this of inactivity. Please feel free to reopen.
