### ISSUE TITLE
isDragReject fails if mime is correct but size is wrong

### ISSUE THREAD

**Issue by jisaacks** [okonet/react-dropzone#363]
When supplying a function to dropzone you are supposed to get an object with properties `isDragActive` and `isDragReject` depending on if a file is hovered and whether or not it will be accepted or rejected.

If the file will be rejected based on it's `accept` mime type it properly sets the those properties.

However if a file will be rejected because it is larger than `maxSize`, it incorrectly reports `isDragActive=true` and `isDragReject=false`

**Comment by okonet** [comment]
That's because it's not possible to get the size or anything but types during the drag. I'll remove the file size validation from the library API soon to remove this confusion.

I don't think this is solvable ATM. Feel free to re-open and submit a PR with the fix if you know the solution.

**Comment by jisaacks** [comment]
Got it. Makes total sense. Thanks for the quick response.
