### ISSUE TITLE
RemoveLink option

### ISSUE THREAD

**Issue by mustafawm** [okonet/react-dropzone#367]
Hello, 

Is there an option (like `addRemoveLinks`) to remove a file after dropping it on the box?

**Comment by okonet** [comment]
I'm not sure what you mean by "remove a file after dropping". Please elaborate.

**Comment by mustafawm** [comment]
Hi @okonet, I was referring to this [addRemoveLink](http://www.dropzonejs.com/#config-addRemoveLinks). Basically, once you drop a file on the box, a hyperlink will/can be displayed to allow the user to remove that file from the queue.

![screen shot 2017-03-01 at 9 53 42 am](https://cloud.githubusercontent.com/assets/13101565/23438190/06fe7048-fe65-11e6-88e0-693a276ff576.png)


![screen shot 2017-03-01 at 9 53 46 am](https://cloud.githubusercontent.com/assets/13101565/23438195/0f2491c6-fe65-11e6-96f9-dfecba88e55e.png)

**Comment by okonet** [comment]
This should not be part of this library and should be implemented by you depending on your UI.
