### ISSUE TITLE
Getting the duration of an audio file on drop

### ISSUE THREAD

**Issue by malimichael** [okonet/react-dropzone#369]
Is it possible to get the duration of audio files on drop? I'm wanting to do something like this

```
  onDrop(files) {
    files.forEach((file) => {
       console.log(file.duration);
    })
  }
```

**Comment by malimichael** [comment]
Anyone else who might want to do this I solved it by doing the following

```
  onDrop(files) {
    files.forEach((file) => {
    const audio = document.createElement('AUDIO');
    audio.src = file.preview;
    audio.addEventListener('loadedmetadata', () => {
       console.log(audio.duration);
    });
  }
```

Not sure if this is the right way to do it but it works for what I'm doing

**Comment by muhilham** [comment]
do you know how to get video duration if file is in .avi format?

**Comment by kumar88kanishk** [comment]
Hi  @malimccalla i am trying to find the duration of a video file after it has been dropped. I implemented your hack but cant get inside loadedmetadata call back. Can you help

**Comment by pbirsinger** [comment]
Seems like `file.preview` is `undefined` for me. Should it be `file.path` ?

**Comment by seanmaisch** [comment]
@muhilham @kumar88kanishk @pbirsinger 

Revisiting this old topic because I was searching for the same solution. I was able to gather the video duration by using this code. In my scenario, I am allowing for a single video upload, hence the `file[0]` array selection. Hope someone finds this helpful in the future!

```
onDrop: (file) => {
	Object.assign(file[0], {
		preview: URL.createObjectURL(file[0])
	});

	const video = document.createElement("video");
	video.src = file[0].preview;

	video.addEventListener("loadedmetadata", () => {
		console.log(video.duration);
	});
}
```
