### ISSUE TITLE
Example of 'function as child' styling

### ISSUE THREAD

**Issue by kgn** [okonet/react-dropzone#372]
I upgraded to the latest version and want to update to the new way of styling Dropzone with `function as child`, however I'm not entirely sure how to do this and the [readme still mentions using styles or classes](https://github.com/okonet/react-dropzone#reacting-to-user-input) so seems should be updated.

**Comment by archieherbias** [comment]
Having the same problem. It seems there are several things that are deprecated:
`style`
`className`
`maxSize`
`minSize`

There is still no clear documentation yet for this one.

**Comment by okonet** [comment]
I'm working on it in https://github.com/okonet/react-dropzone/pull/313

> there are several things that are deprecated

None of them is deprecated yet but they will go away in the next major breaking release. That's why I suggest not to use them anymore.
