### ISSUE TITLE
How to get file download progress

### ISSUE THREAD

**Issue by kekeoki** [okonet/react-dropzone#374]
I want a way to fully confirm the attachment is loaded into the browser, not sure how to do this with react-dropzone. Do you have an on progress callback?

**Comment by archieherbias** [comment]
@kekeoki : There is an `onDrop` function which is triggered when files are selected. It receives two parameters: `accepted` and `rejected`, they are both arrays.
You can have a preview with the files that you selected. For example you selected one file, you can have its preview url by calling `accepted[0].preview`

Hope that makes sense :+1:

**Comment by cnolimit** [comment]
As I understand we have access to the two parameters which deliver the files that have or have not been uploaded, is there any way to determine when a file is in the process of being uploaded and when it has been completed. The information could then be used to determine when to trigger a loader.

**Comment by kekeoki** [comment]
Sorry, I didn't do a good job of explaining.
Really what I want to do is take the file and drop it into a variable (use file reader to load it), you can go ahead and close this if you want.

**Comment by okonet** [comment]
Since this isn't an issue with the library, I'm closing it. Please use StackOverflow for questions.
