### ISSUE TITLE
isDragReject is always false in Safari

### ISSUE THREAD

**Issue by leogiertz** [okonet/react-dropzone#377]
The easiest way to see an example of this bug manifesting itself is to:
* Go to http://okonet.ru/react-dropzone/ in Safari
* Drag something else than an image onto the dropzone.
* Observe that it turns green.

Doing the same in Chrome will turn the dropzone red. Attaching a screenshot.
<img width="959" alt="screen shot 2017-03-09 at 17 38 56" src="https://cloud.githubusercontent.com/assets/124863/23760203/502eb440-04ef-11e7-9bfe-b3ca0b9f899b.png">

**Comment by leogiertz** [comment]
Happens with 3.11.0 for me.

**Comment by okonet** [comment]
It looks similar to #362. Please feel free to investigate this issue and provide more details. I assume this is also a browser issue.

**Comment by tt-mikeolson** [comment]
Based on http://caniuse.com/#feat=dragndrop , it seems like Safari can't display a rejected status on dropzones until they support `dataTransfer.items`. Currently only Chrome supports it.

**Comment by mwolson** [comment]
Based on http://caniuse.com/#feat=dragndrop , it seems like Safari can't display a rejected status on dropzones until they support dataTransfer.items. Currently only Chrome supports it.

**Comment by kamas06** [comment]
+1
Same happens in IE11

**Comment by okonet** [comment]
This is a known issue of HTML5 drag'n'drop implementation and currently can't be fixed AFAIK. If someone have an idea for a fix, please submit a PR and re-open the issue.
