### ISSUE TITLE
Style is deprecated, but style is still needed

### ISSUE THREAD

**Issue by morulus** [okonet/react-dropzone#379]
Take a look at [this](https://github.com/okonet/react-dropzone/blob/master/src/index.js#L226).
We have default style here. This style forms when there is no user props `!className && !style && !activeStyle && !rejectStyle`.
```js
if (!className && !style && !activeStyle && !rejectStyle) {
      style = {
        width: 200,
        height: 200,
        borderWidth: 2,
        borderColor: '#666',
        borderStyle: 'dashed',
        borderRadius: 5
      };
      activeStyle = {
        borderStyle: 'solid',
        backgroundColor: '#eee'
      };
      rejectStyle = {
        borderStyle: 'solid',
        backgroundColor: '#ffdddd'
      };
    }
```

`className`, `style`, `activeStyle`, `rejectStyle` are deprecated. It is good, perhaps. But what if I do not need to see default styling? I do not need `width: 200px, height: 200px`, etc. Adding function as children (as you recommend in deprecate block) did not disable default style.
How can I customize a style of the top container, keeping the console clean?

**Comment by okonet** [comment]
See the discussion here #364
