### ISSUE TITLE
className deprecation notice

### ISSUE THREAD

**Issue by felds** [okonet/react-dropzone#386]
All className props are being marked as deprecated but there are no alternatives in the docs on how to fix that.

```jsx
<Dropzone
      className="uploader"
      activeClassName="uploader--active"
      rejectClassName="uploader--reject"
/>
```

![screen shot 2017-03-15 at 12 39 00](https://cloud.githubusercontent.com/assets/139979/23959821/f79933b0-0984-11e7-96f1-2de681269916.png)

**Comment by okonet** [comment]
See #364

**Comment by felds** [comment]
@okonet how are the docs going? do you want any help?

**Comment by okonet** [comment]
Help is always appreciated but now it's mostly about landing this https://github.com/styleguidist/react-styleguidist/pull/330 and finishing the "design"
