### ISSUE TITLE
.csv file MIME type is empty in Windows browser

### ISSUE THREAD

**Issue by RoyLiou** [okonet/react-dropzone#391]
Hi,
I use component set props accept='text/csv'. However, When I select .csv file and callback function return empty array in Windows browser(IE, Edge). MacOS not this wrong.

I've try to find this issue.
Because Windows browser not known text/csv type ,so fileAccepted function return false
https://msdn.microsoft.com/en-us/library/ms775147(v=vs.85).aspx

In my opinion we could add file extension check in fileAccepted.
Thanks.

(I apologize for English not my native language if made confused)

**Comment by okonet** [comment]
It won't be supported by the `input` element even if we'll implement it in JS. There is a part in the README re this.
