### ISSUE TITLE
Deprecation warning with style/className

### ISSUE THREAD

**Issue by turnerhayes** [okonet/react-dropzone#394]
I'm getting the following deprecation error: `Prop style is deprecated. Use function as children to style dropzone and its contents.`. Fair enough, I use children, but removing the `style` (or `className`) prop causes the default styling to reappear. What's the preferred way to prevent default styling with the deprecation of those props?

Edit: Also, how do I set a class name on the wrapper (for targeting with CSS, e.g.) without `className`?

**Comment by okonet** [comment]
https://github.com/okonet/react-dropzone/pull/364#issuecomment-282334432
