### ISSUE TITLE
File dialog not opening 3.12.x when used inside a modal

### ISSUE THREAD

**Issue by tarun-dugar** [okonet/react-dropzone#397]
So, I recently upgraded the version from **3.4.0** to **3.12.x**. 

After doing this, the file dialog stopped opening when used inside a modal(tried with `react-modal` and `react-modal-dialog` so its not a modal issue) but works when not used inside a modal. I couldn't find the cause but just letting you guys know. 

In the meantime, I have downgraded to **3.4.0** and it works completely fine. Let me know if you need more details!

**Comment by okonet** [comment]
Yes, a reproducible repository on GitHub would be a great start. A PR with a fix would be even better.

**Comment by okonet** [comment]
Closing of inactivity
