### ISSUE TITLE
Memory leak when image files are removed

### ISSUE THREAD

**Issue by stevemao** [okonet/react-dropzone#398]
object URL is created `onDrop` if `!disablePreview` but never destroyed. [They are not released automatically unless document is unloaded.](https://developer.mozilla.org/en-US/docs/Using_files_from_web_applications#Using_object_URLs)
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1. show a preview of the dropped file ([follow the example in readme](https://github.com/okonet/react-dropzone#manual-upload))
1. remove a file by 
```js
this.setState({
      files: []
});
```
or whatever
1. The object URL is not released and still in memory.

**What is the expected behavior?**
The object URL should be released once `files` is changed. This could be done in the hook [onDrop](https://github.com/okonet/react-dropzone/blob/02e1416/src/index.js#L127). Before [object URL is created](https://github.com/okonet/react-dropzone/blob/02e1416/src/index.js#L142), release the old ones by calling `window.URL.revokeObjectURL(objectURL);`
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
The master branch of react-dropzone

**Comment by okonet** [comment]
Thanks for pointing to it. As I understand this should go to the documentation since 🎯 react-dropzone doesn't manage dropped files by itself. do you mind to create a PR against styleguide branch?
