### ISSUE TITLE
React 15.5.x Support

### ISSUE THREAD

**Issue by ncphillips** [okonet/react-dropzone#403]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [X] I want to propose a feature

**What is the current behavior?**
Works with React 15.4.x and below

**What is the expected behavior?**
Work with React 15.5.x, which has deprecated several things and moved PropTypes to an external dependency.

**If this is a feature request, what is motivation or use case for changing the behavior?**
I'll want to upgrade to React 15.5.x eventually.

**Comment by okonet** [comment]
It would be great if you could submit a PR that implements it!

**Comment by DanielZhu** [comment]
@ncphillips I want to upgrade react to 15.5.x as well...

**Comment by okonet** [comment]
@DanielZhu submit a PR!

**Comment by jochenberger** [comment]
`react-dropzone` works with 15.5 alright, it just causes some warnings.

**Comment by jochenberger** [comment]
See  #405
