### ISSUE TITLE
How to delete an image?

### ISSUE THREAD

**Issue by RashidMalikov** [okonet/react-dropzone#407]
How to delete an image?
How to add button to delete an image?

**Comment by michaelsync** [comment]
Why was this closed? I am looking for something similar to this example http://reactdropzone.azurewebsites.net/example/ .. (e.g. adding a 'remove file' link. )

**Comment by rkmarks** [comment]
@michaelsync the reason this was closed as this wasn't really an issue. More just a question for guidance.  However in your consuming component you can create a function that removes the file from state. Also you can add a ref to the `react-dropzone` component so you can get to the state of the dropzone component and remove the file from the state there. i have attached a gist of something i used in one of my components. 

https://gist.github.com/rkmarks/3316914da046aa1b92930c32fb9cc644
