### ISSUE TITLE
When multiple is set to false the rejectClassName is not shown when multiple files are dragged in.

### ISSUE THREAD

**Issue by plee-nm** [okonet/react-dropzone#409]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Set multiple to false and have a rejectClassName
2. Drag 2 files onto the dropzone

**What is the expected behavior?**
The reject class is added to the dropzone element.

**Comment by okonet** [comment]
Not sure what's happened but it seems this wasn't released. Investigating.
