### ISSUE TITLE
property documentation has been removed from readme.md

### ISSUE THREAD

**Issue by jackgeek** [okonet/react-dropzone#414]
I notice that the readme.md documentation has had the props removed.

This version:  
https://github.com/okonet/react-dropzone/blob/4e127018acd68b92c2a2862f66caa0bc3a3f9244/README.md

... has a Features heading under which the properties are documented.

The current readme.md is missing prop documentation.

**Comment by okonet** [comment]
I'm not sure what you mean If you see a problem with the documentation, you're welcome to fix it.

**Comment by beezischillin** [comment]
the current documentation does not mention anything related to what props your component accepts, including the maxSize bits. If that could be rectified, it would probably helpful for people in the future.

Thank you for your work!

**Comment by okonet** [comment]
Oh I got it. The reason for that is the automatically generated documentation with examples that can be found https://react-dropzone.netlify.com (for now, will probably move to `.js.org`)
