### ISSUE TITLE
Re-renders unnecessarily when props do not change

### ISSUE THREAD

**Issue by dlindenkreuz** [okonet/react-dropzone#419]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Dropzone re-renders unnecessarily when props do not change.

**If the current behavior is a bug, please provide the steps to reproduce.**

Use react-dropzone with [why-did-you-update](https://github.com/garbles/why-did-you-update) and find that re-renders are avoidable. Alternatively put a `console.log` in react-dropzone's `render()` function.

**What is the expected behavior?**
Do not re-render when props do not change. Maybe the component should extend [`React.PureComponent`](https://facebook.github.io/react/docs/react-api.html#react.purecomponent) instead of `React.Component`.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Performance 🤓 We use this at a critical point in our app.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
react-dropzone@3.13.1 (latest version at the time of writing)

**Comment by okonet** [comment]
IMO such optimizations should live in the userland since they might lead to unexpected behavior. Dropzone component itself is very simple so it won't cost much to re-render. If the contents of it are complex, they have to be optimized.
