### ISSUE TITLE
Dropping from an open file picker crashes chrome

### ISSUE THREAD

**Issue by 2718e** [okonet/react-dropzone#420]
**Do you want to request a *feature* or report a *bug*?**

- I found a bug

**What is the current behavior?**
In Chrome If you click the dropzone to open a file picker, then drop *from* the open file picker *to* the dropzone, then hit cancel on the file picker, then (sometimes) chrome will become non responsive and crash

**If the current behavior is a bug, please provide the steps to reproduce.**

1. click the dropzone to open a file picker
2. Drag and drop a file *from* the file picker *to* the dropzone
3. Close the file picker by clicking cancel ( *not* by clicking open )

Sometimes (but not always) chrome becomes non responsive and force closes.

**What is the expected behavior?**

Either of:
1. Dropping shouldn't be allowed while the file dialog is open.
2. It should work the same as any other drop and not crash the browser.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Chrome Version 57.0.2987.133 (64-bit)
Windows 7 professional Service pack 1
react dropzone version 3.13.1. (Have also managed to reproduce this on the demo site https://react-dropzone.netlify.com/)

**Comment by joedski** [comment]
As noted in https://github.com/enyo/dropzone/issues/669 this seems to be a Chrome/Chromium (and Opera?!) issue.
- [Issue in Chromium Bug Tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=388661) (Listed as `WontFix`...)
- [Thread on Google Products thinger about Chrome](https://productforums.google.com/forum/#!topic/chrome/x2vNTnlIcBs;context-place=forum/chrome)
