### ISSUE TITLE
React 14 compatibility

### ISSUE THREAD

**Issue by RickyMarou** [okonet/react-dropzone#425]
Hello,

The peer dependencies for this package are listing react 14 alongside react 15.

```
"peerDependencies": {
    "react": "^0.14.0 || ^15.0.0"
  }
```

However, as of version `3.12.4`, the package has a dependency on the `prop-types` packages, which is throwing warning for people still using react 14.

```
Warning: Failed Context Types: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them. Read more at http://fb.me/use-check-prop-types Check the render method of `[NAME OF COMPONENT]`
```

Maybe consider removing react 14 has a peer dependency and only have 15+ ? Otherwise there seems to be a workaround this issue if you want to keep this package fully compatible with react 14 :  https://github.com/reactjs/react-redux/issues/669

Cheers and thanks for your work :)

**Comment by okonet** [comment]
Hmm, should it be just updated to `^0.14.9`? https://github.com/reactjs/react-redux/issues/669#issuecomment-293622657

**Comment by RickyMarou** [comment]
yes i was on 14.8 but updating to 14.9 addresses this. Thanks for taking the time to address this.
