### ISSUE TITLE
Add disable attribute

### ISSUE THREAD

**Issue by Mangatt** [okonet/react-dropzone#428]
Hi, I think that it would be useful to add `disable` attribute to dropzone.

There are certainly cases in which you want just disable dropzone, but in current situation you have to remove dropzone entirely and then append it again to achieve this effect.

**Comment by okonet** [comment]
That sounds like a good opportunity for a PR! Please feel free to create it and let's continue discussion there.

**Comment by okonet** [comment]
Closing of inactivity

**Comment by Dzixxx** [comment]
+1 for disable

**Comment by MV88** [comment]
Hello,
My workaround was adding this to the style of the div parent:
{ pointer-events: none }
