### ISSUE TITLE
[Docs] Clarify that max and min size are accepted as bytes.

### ISSUE THREAD

**Issue by ncphillips** [okonet/react-dropzone#432]
The dropzone library itself uses MB, but react-dropzone uses Bytes. 

It would be good to clarify this

**Comment by okonet** [comment]
Feel free to create a PR

**Comment by okonet** [comment]
Keep in mind those will be deprecated soon

**Comment by ncphillips** [comment]
Really? What will replace them?

**Comment by okonet** [comment]
Nothing really. This should be then done in onDrop callback. Search for a discussion about it.

**Comment by okonet** [comment]
@ncphillips here is the relevant discussion: https://github.com/okonet/react-dropzone/issues/321

**Comment by okonet** [comment]
I'm closing this one since props will be deprecated soon.

**Comment by ncphillips** [comment]
Thanks @okonet

**Comment by josephecombs** [comment]
@okonet is there a example somewhere in the docs with onDrop being used to validate dropped files?

**Comment by okonet** [comment]
Not yet. Fancy to create one? See /examples

**Comment by josephecombs** [comment]
Sure. Hopefully I will do this today.
