### ISSUE TITLE
resizeWidth , resizeHeight and resizeQuality will this be implement in react dropzone

### ISSUE THREAD

**Issue by Uthpala** [okonet/react-dropzone#438]
In the newest version of dropzone we have the ability to configure resizeWidth, resizeHeight and resizeQaulity 

http://www.dropzonejs.com/#config-resizeWidth

Is there a plan to add this feature soon ?

**Comment by okonet** [comment]
No, the focus of this library is to remain as small as possible and focus on one thing — drag'n'drop files interactions. The mentioned feature is an image specific one and thus should be implemented by users. Thanks React composabilty it's straightforward to do so without introducing bloat to small libraries like this one.

**Comment by Aarbel** [comment]
@okonet @Uthpala do you know a library to resize an inage client side before upload ?
