### ISSUE TITLE
Client-side resizing and compression

### ISSUE THREAD

**Issue by danjebs** [okonet/react-dropzone#439]
**Do you want to request a *feature* or report a *bug*?**
- [ ] I found a bug
- [x] I want to propose a feature

**What is the current behavior?**
There is currently no way (it seems) to resize an image on the client-side. It's easy enough on the server-end, but UX-wise it would be nice to do on the client side.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Often users are uploading images from mobile devices or tablets, which take really large images. Ideally these would be compressed/resized at the client end before being uploaded. 

Similar to the discussion on Enyo's DropZone:
https://github.com/enyo/dropzone/issues/781

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
N/A

**Comment by okonet** [comment]
You can process images on the client-side in the `onDrop` callback.

**Comment by danjebs** [comment]
@okonet I realise that there are places to process images as such.

I was suggesting that this be added as a built-in feature because it would be useful for myself and (judging by the thread on Enyo's DropZone) many other developers. It's in the name of making this a better piece of software.

I get that you are busy and are probably flooded with feature requests, but I'm urging that you consider including this. Or, perhaps there are good reasons why it is not included, but they aren't immediately clear. Nor have I seen any implementation pointers that work with this specific package, either here or on SO.

At any rate, I'll figure out how to do it...but I don't think I'm the only one wondering.

**Comment by okonet** [comment]
Here I try to explain why such features will never be part of this library: https://github.com/okonet/react-dropzone/issues/438#issuecomment-307031166

**Comment by danjebs** [comment]
OK thanks for clarifying, that makes sense.
