### ISSUE TITLE
isDragActive behavior is misleading

### ISSUE THREAD

**Issue by oyeanuj** [okonet/react-dropzone#440]
**Do you want to request a *feature* or report a *bug*?**

I found a bug

**What is the current behavior?**
Something that kept tripping me up is that `isDragActive`'s behavior does not match the name. It is set to true only when all files are going to be accepted and false when even one of the files is false.

**If the current behavior is a bug, please provide the steps to reproduce.**

Drag two files in the examples provided (Accepting Specific File Types) - one which will be accepted, and one which will be rejected.

**What is the expected behavior?**
Even if one of the many files being dragged is going to be rejected, `isDragActive` should be true since the drag is indeed active (and contains files to be accepted).

I feel like we are trying to pack in a few different behaviors into two props. The behaviors as I see that we are trying to get are (might not be the best names below)  -
1. `isDragActive`: Is the user dragging files at the moment?
2. `willAnyFileBeAccepted`: Are any of the files in the drag going to be accepted?
3. `willAnyFileBeRejected`: Are any of the files in the drag going to be rejected?

Additionally, I would suggest thinking of this and #356  together as they are related - rethink props which are passed to children for overlays.

Thank you!

**Comment by okonet** [comment]
I like the proposal. Initially this library only had `isDragActive` and `isDragRejected` came later as a PR. I'm ready to accept such PR if you're ready to create it.

I'm not totally sure about name proposals, though. It seems that `willAnyFileBeAccepted` is limiting too. What about `willAllFilesBeAccepted`? Same with rejected. Keeping in mind we want to push decisions to users as much as possible (API should allow to do anything!), I think we should replace `isDragActive` and `isDragReject` with something more generic like drag state and files validation state.

Thoughts?

**Comment by oyeanuj** [comment]
@okonet Thanks for the response. I am open to other ways of solving it as well.  Couple of more different options - 

1. The most flexible would be passing individual files and a `validateFile` method so that they can make those check themselves?

2. Run the check on all files and separate them into two arrays, say, `acceptableFiles`, `rejectableFiles`?

Also,
> I think we should replace isDragActive and isDragReject with something more generic like drag state and files validation state.

Could you elaborate more?

**Comment by okonet** [comment]
@oyeanuj the only thing that can be validated now is the mime type using my implementation of https://github.com/okonet/attr-accept. I think that the 2 is much easier to implement and fits better into current code base. What the API will look like after that change?
