### ISSUE TITLE
Support of MAC Packaged files (.pages, .key) as is, without zipping.

### ISSUE THREAD

**Issue by 1459** [okonet/react-dropzone#453]
**Do you want to request a *feature* or report a *bug*?**
I want to propose a feature: Support MAC packaged files like pages, keys without zipping them.

**What is the current behavior?**
Currently if a packaged file is dragged and dropped the file is getting zipped and uploading this is in Safari. But in Chrome if a packaged file is dragged and dropped the files inside the package are getting extracted and displaying as individual files.

**What is the expected behavior?**
Packaged files should be uploaded as is, and not suppose to zip or extracted.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Browsers: Safari 10.1.1, Chrome Version 59.0.3071.115,
Operating System: Mac Sierra
react-dropzone version: 1.4.1

**Comment by okonet** [comment]
I think this is isn't possible with web APIs. Safari supports that because it's a platform thing. If you know how to implement this, please feel free to reopen it and submit a PR.
