### ISSUE TITLE
Selecting multiple files doesn't work on Chrome (Android)

### ISSUE THREAD

**Issue by taikn** [okonet/react-dropzone#456]
**Do you want to request a *feature* or report a *bug*?**

- [ x ] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
When i try to select multiple files i get only second last file as a callback

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Open Chrome browser on Android
2. Navigate to https://react-dropzone.js.org/#basic-example
3. Click on react-dropzone
4. Select few files and click done
5. Only one file is appearing in the list of Dropped Files 

**What is the expected behavior?**
All selected files should be returned within callback

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

Chrome 59.0.3071.125
Android 7.1.1
React-Dropzone 3.13.3

**Comment by taikn** [comment]
Nevermind, seems to be browser/OS limitation

**Comment by ggarcia92** [comment]
Hi @taikn I am using chromium browser and I have the same issue. Instead when I tried with Firefox it works. I think this issue should be reopened as ***Selecting multiple files doesn't work on Chrome***

**Comment by rolandjitsu** [comment]
@ggarcia92 please provide a reproducible example as the basic example works just fine in Chrome `71.0.3578`. Or at least the version you're using.

**Comment by ggarcia92** [comment]
Hi @rolandjitsu thanks for your answer but it works, thanks and apologies. Regards
