### ISSUE TITLE
Feature Request: Styling the File List

### ISSUE THREAD

**Issue by jonfairbanks** [okonet/react-dropzone#457]
**Do you want to request a *feature* or report a *bug*?**

- I want to propose a feature

**What is the current behavior?**

- Dropzone's file list uses a default style (no style).

**If the current behavior is a bug, please provide the steps to reproduce.**

1. According to the docs, styling is supported, but these values seem to apply to the dropzone only. There is no option to stylize the file list. Ideally, this style would be separate from the dropzone's style. 

**What is the expected behavior?**

- The ability to stylize the file list. 

**If this is a feature request, what is motivation or use case for changing the behavior?**

- We've heard from users who used dropzone: "I added an attachment in the UI, but no attachment was saved". After investigating, the attachment was uploaded just fine. The issue was that the file list is small and text only so the user missed it. 

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

- react-dropzone@3.10.0

**Comment by okonet** [comment]
Hey! Thanks for opening it. Do you want to create a PR that will fix that?

**Comment by okonet** [comment]
I'm not sure, though, what this issue is about.

> The issue was that the file list is small and text only so the user missed it.

What is the file list?

I'm closing this one of inactivity. Feel free to re-open.
