### ISSUE TITLE
Include webkitRelativePath or fullPath property in each file object

### ISSUE THREAD

**Issue by caseychoiniere** [okonet/react-dropzone#459]
- [X] I want to propose a feature

**What is the current behavior?**

Currently the file list that is returned from the onDrop event is missing the `webkitRelativePath` and/or the `fullPath` property. This is what is returned:
```javascript
{
  name: "Screen Shot 2017-06-05 at 12.33.12 PM.png",
  lastModified: 1496684001000,
  lastModifiedDate: MonJun05201710: 33: 21GMT-0700(PDT),
  webkitRelativePath: "",
  size: 41890,
  type: "image/png",
  webkitRelativePath: ""
}
```

If I use a standard input or other drag and drop implementations the `webkitRelativePath` or `fullPath` property is populated with a value in each file in the file list

**What is the expected behavior?**

I would expect the file objects in the returned file list to have all available (non deprecated) properties included. I would expect this:
```javascript
{
  name: "Screen Shot 2017-06-05 at 12.33.12 PM.png",
  lastModified: 1496684001000,
  lastModifiedDate: MonJun05201710: 33: 21GMT-0700(PDT),
  webkitRelativePath: "",
  size: 41890,
  type: "image/png",
  webkitRelativePath: "folder_1/folder_2/folder_3/Screen Shot 2017-06-05 at 12.33.12 PM.png"
}
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

I am implementing directory uploads and in order to rebuild the folder structure I need to access the `webkitRelativePath` or `fullPath ` property in each file object. 

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

Latest react-dropzone version

Thanks for your time and consideration!

**Comment by okonet** [comment]
Hmm, I'm not modifying anything but `preview` property. See https://github.com/okonet/react-dropzone/blob/master/src/getDataTransferItems.js

**Comment by caseychoiniere** [comment]
I think this is just the difference between using an input or a dropzone. When files are dropped the `webkitRelativePath` or `fullPath` doesn't seem to be included. I was able to confirm this by building my own drag and drop. I apologize for the noise here. Closing this issue.

**Comment by okonet** [comment]
@caseychoiniere it's not noise but a valuable feedback and I thank you for that. 

To the issue: they probably work around it somehow. If you're eager to find out and implement it here, I'd be glad to accept a PR.

**Comment by okonet** [comment]
@caseychoiniere interestingly I have this duplicate issue saying

> don't bother trying to get the path, you can't get it

https://github.com/react-dropzone/react-dropzone/issues/477

**Comment by caseychoiniere** [comment]
Oh man, I just spent 30 minutes or so to write a very long and relevant response to this but then navigated away from the page and lost my work before publishing the comment. So here's the short version.

The `webKitRelativePath` property is only available when you have the `webkitdirectory` attribute set on your input or when using the directory reader in the HTML5 File API to read directories from a dropped folder on the dropzone. 

It seems like this functionality is beyond the current intended scope of react-dropzone.

In the past you have said that this functionality should be part of a separate npm package and not part of react-dropzone. #174 

I know that @quarklemotion had tried to roll his own directory handling script and was going to publish an npm package. I actually tried using his script and this is where I ran into this problem in the first place. Not sure why `webKitRelativePath` isn't exposed there and I'm not going to work on figuring it out because there are already viable options available to people. 

I had success using Dropzone.js to just make my own React component in about 30 minutes and it handles directories out of the box. If this doesn't work for others they could try applying (open source) code from Dropzone.js ([Relevant Code Here](https://github.com/enyo/dropzone/blob/master/dist/dropzone.js#L944)) or from another open source library like [Uppie.js ](https://github.com/silverwind/uppie/blob/master/uppie.js) to react-dropzone in there own project to get the functionality they need. 

Anyways, hope this helps some folks.

**Comment by alexandis** [comment]
The question is now how to make use the relative path at SERVER... :) I use Drop Zone to upload files to server and I want to RECREATE a directory structure. However, I cannot put in correspondence files and the respective relative paths... Because I cannot pass them all as a single collection (IFormFile[]) to the server.
