### ISSUE TITLE
Active state not visible in Safari

### ISSUE THREAD

**Issue by okonet** [okonet/react-dropzone#461]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

Active state on drag missing in Safari

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Drag over some files
1. See how in Safari no visual feedback is given

**What is the expected behavior?**

It should apply active styles

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by stas-lesiuk** [comment]
@okonet What is the actual state of this issue? Is it merged? Asking because when I clone repo and run `npm start`, the active state is PRESENT of Safari, however, when I add use react-dropzone as a dependency in my project, activeStyle & activeClassName doesn't work on Safari. I've tried with different versions of package, but didn't succeed.

**Comment by stas-lesiuk** [comment]
@okonet What is even more strange is that when I clone the 'react-dropzone' repo and adjust my import statement to 'react-dropzone/src', then the active state works on Safari perfectly as well. Could you tell me which library version is used on those official examples?

**Comment by okonet** [comment]
It’s always master

**Comment by stas-lesiuk** [comment]
Well what I mean is which version of react-dropzone is used on master? Can I get it via npm? Using `npm show react-dropzone versions` I see a bunch of versions, with major starting on 0.1.0 and up to 4.2.12, so I tried with every major version, but the activeClassName didn't work on Safari. However, it did work when I copy the files from cloned repo & use them directly, not as a node module. If that's not a version issue, do you have any idea what may cause that?

**Comment by okonet** [comment]
Master is the latest version from the npm. We’re using semantic release.

**Comment by okonet** [comment]
Not really, please investigate and let us know. Or, even better, submit a PR with a fix. Thanks for digging!
