### ISSUE TITLE
File Dialog requires selecting file two times, does not even upload at all in Safari 10.1.1

### ISSUE THREAD

**Issue by RussYoung** [okonet/react-dropzone#470]
I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
You click to open the file dialog, select a file and click open.  The dialog goes away and then comes back again.  The second time you select a file and click open, it calls onDrop and accepts the file.

In Safari, the file dialog appears, you select the file, then the dialog goes away and never comes back.  onDrop is never called.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is the simple component that exhibits this behavior:

class MediaUpload extends Component {
  constructor(props) {
    super(props);
    this.dropZoneRef = null;
  }

  render() {
    return (
      <div className="simple-media-component">
        <Dropzone
          accept="image/*"
          ref={(node) => { this.dropZoneRef = node; }}
          onDrop={(accepted, rejected) => {
            if (rejected.length) {
              const list = rejected.map(item => `${item.name} - ${item.size}`);
              alert(`Rejected\n${list.join('\n')}`);
            }
            if (accepted.length) {
              const list = accepted.map(item => `${item.name} - ${item.size}`);
              alert(`Accepted\n${list.join('\n')}`);
            }
          }}
        >
          <span>Drag and drop images here or</span>
          <Button
            kind="text"
            onClick={() => { this.dropZoneRef.open(); }}
            label=" click here to browse"
          />
        </Dropzone>
      </div>
    );
  }
}
**What is the expected behavior?**
The file dialog should only appear one time, and allow upload of the file the first time.
In Safari, the dialog only appears once, but never calls onDrop

browser version: Version 59.0.3071.115 (Official Build) (64-bit)
macOs: Sierra 10.12.5
react-dropzone version: 3.13.4
Safari: 10.1.1

**Comment by drblmb** [comment]
This is actually an issue I wrote, but submitted while signed in on a different computer and account.

**Comment by drblmb** [comment]
I think I understand now what is happening.  I had my button onClick() which called open() inside the children of DropZone.  Since DropZone already has a click event, it was processing two click events.
