### ISSUE TITLE
Maybe disable auto complete on input element by default

### ISSUE THREAD

**Issue by dominic-p** [okonet/react-dropzone#475]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Firefox throws a SecurityError. I think the reason for this is [described here](https://stackoverflow.com/a/37972457/931860). Basically, I think Firefox tries to set the input element's value which throws the error. When I pass `{ autoComplete: 'off' }` to Dropzone in the `inputProps` the problem goes away.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Drop a file or pick one using the file UI
2. Refresh the browser

**What is the expected behavior?**
No error

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Firefox 54.0.1 Windows

Thanks for the great component, btw. :)

**Comment by okonet** [comment]
Would you mind creating a PR for this? Thanks!

**Comment by dominic-p** [comment]
Done. See #476.
