### ISSUE TITLE
Upload example won't work with req.attach

### ISSUE THREAD

**Issue by bdefore** [okonet/react-dropzone#72]
Should use FormData instead. See https://github.com/visionmedia/superagent/issues/746

**Comment by okonet** [comment]
Related to #123

**Comment by Surreal9** [comment]
Even with FormData I still can't get upload to work. I'm using the code
```
export function startUpload(file) {
  console.log('trying to upload file', file);
  const req = request.post('/upload');
  const data = new FormData();
  data.append('asset', file);
  req.send(data);
  return req.promise();
}
```
However it feels like the 'file' object isn't what is expected. When I look at my request body in Charles I see: 
```
------WebKitFormBoundaryYp3vrVzenpHEwts8
Content-Disposition: form-data; name="asset"

[object Object]
------WebKitFormBoundaryYp3vrVzenpHEwts8--
```

Is there some other way to get the data that superagent is expecting?

**Comment by Surreal9** [comment]
Actually never mind my comments.. I'm using Redux and attempted to add data to the object returned by using Object.assign and apparently that changed it from being a 'file' object type, which broke the send.. deleting my comments..
