### ISSUE TITLE
Drag & Drop From Application Non-Functional in OS/X / Chrome

### ISSUE THREAD

**Issue by pcrumm** [okonet/react-dropzone#74]
To test this, pop open the demo in Chrome and head over to an OS/X application like iTunes.

Select one or more files (I am using 3 for the sake of testing) and drag them into the drop area. The hover event will fire, but `onDrop` never occurs and the files are never actually uploaded.

**Comment by nanot1m** [comment]
Same issue in Chrome 45 on OS X El Capitan

**Comment by okonet** [comment]
I assume this is an issue with Chrome not providing any information to `dataTransfer` object?

**Comment by newsiberian** [comment]
The same issue on Linux. I've tried to drop images from kde dolphin and from krusader to Firefox, Chromium, but onDrop event never reached.

**Comment by newsiberian** [comment]
Only after these changes:
```
  onDragOver(e) {
    e.preventDefault();
    e.stopPropagation();
    return false;
  }
```
I was able to go into the onDrop(). Btw, there was a PR [#37](https://github.com/paramaggarwal/react-dropzone/issues/37). Why this code was removed?

**Comment by okonet** [comment]
Can you guys create a PR for this one?

**Comment by Lendar** [comment]
It's a bit weird but  #114 actually introduced _that_ bug.

For the reference, scenario:

1. Open react-dropzone 3.3.0 at http://paramaggarwal.com/react-dropzone/
2. Drop a music file from iTunes

Chrome Version 49.0.2593.0 dev (64-bit)
OS X 10.11.2 El Capitan

Expected: `Dropped files` files appears
Result: nothing appears (except the state when you drag over). __`onDrag` isn't fired__

I had to revert the fix (I want to 3.2.2) to get iTunes + dropzone working again.

Any ideas what to check? Also, http://gaearon.github.io/react-dnd/examples-dustbin-multiple-targets.html (native file) works currently with my chrome and OS X.

**Comment by Lendar** [comment]
Re-checked it once again on different project. My previous statement was not fully correct.

#### My observations

1. #114 from @newsiberian actually introduces the bug in projects with `react-dnd`
2. v3.2.2 does not have this bug in projects with `react-dnd`
3. v3.2.2 has this bug in projects without `react-dnd`

#### Conclusion

Iit depends whether there is another `onDragOver` listener in the project.

__DND from apps works only if there is a `onDragOver` listener that mutates `e.dataTransfer`.__

#### Another fix

Here is what works for me on both my projects. I took the idea from dropzone 1.x:

```diff
   onDragOver(e) {
     e.preventDefault();
     e.stopPropagation();
+    e.dataTransfer.dropEffect = 'copy';
     return false;
    }
```

But fix is too weird for PR. I hope someone will confirm/deny it or clarify what's going on.

**Comment by okonet** [comment]
Seems legit to me for PR. If this fixes the issue I'm happy to merge it. 

Regards,
Andrey Okonetchnikov

**Comment by Lendar** [comment]
Would be happy if @pcrumm or @nanot1m tried both original fix and my fix to see if it works for their projects.

1\. Original:

    npm i react-dropzone@3.3.0

2\. And mine:

    npm i lendar/react-dropzone#fix-osx-apps-dnd

**Comment by systemizer** [comment]
Hey,

Any reason why this wasn't merged in? I having the same problem, and using Lendar's branch fixes it. I'm happy to open a PR with the same change if that's what you need.

thanks,
rob

**Comment by okonet** [comment]
@systemizer the reason is — there is no PR for that yet. Fancy to create it? If you're up to, please also add tests for this case.

**Comment by okonet** [comment]
I've just published https://github.com/okonet/react-dropzone/releases/tag/3.6.0 that should fix it.
