### ISSUE TITLE
Supporting Radium

### ISSUE THREAD

**Issue by kumarharsh** [okonet/react-dropzone#85]
Hi, while looking at the source code, it seems like the module may not *fully* support [Radium](https://github.com/formidablelabs/radium) yet, mainly due to this restriction:

```js
style: React.PropTypes.object,
activeStyle: React.PropTypes.object,
```
For Radium can accept an array of style objects and merge them. Would you be willing to accept a PR which would fix this?

**Comment by okonet** [comment]
Sure. Go ahead and submit a PR

**Comment by okonet** [comment]
Since I don't use Radium and you didn't create a PR yet, I'll close it for now. Still would accept a PR for it.
